# -*- coding: utf-8 -*-
"""
Chapter 06 : Metacognition & Self-Regulation.
Expansions for each of the 24 strategies on the infographic.
"""

EXPANSIONS = {
    "01": {
        "what": "Planning starts with a specific, close-at-hand goal rather than a general aim. Not do well in this essay, but this paragraph will make one claim and support it with two pieces of evidence.",
        "why": "Zimmerman's forethought phase begins with goal setting, and his research distinguishes proximal goals, which are specific and near, from distal ones, which are general and remote. Proximal goals give the learner something to monitor against during the task. A vague aim gives them nothing to check, so monitoring doesn't happen.",
        "how": [
            "Before students start, ask them to write what a good answer to this question would contain.",
            "Insist on specifics rather than adjectives. Detailed is not a goal.",
            "Keep the goal visible while they work.",
            "Return to it at the end and ask whether it was met.",
        ],
        "tech": "Shared success criteria on screen give everyone the same reference point, and keep it visible for the whole task rather than for the first minute.",
        "watch": "Goals that are really instructions in disguise don't develop planning. The student has to make the decision for it to be planning.",
    },
    "02": {
        "what": "Teach the content before expecting students to regulate their learning of it. Metacognition works on knowledge; it doesn't substitute for it.",
        "why": "Willingham's argument is that metacognitive strategies are largely domain-general while the ability to use them well isn't. You can't judge whether your understanding of a topic is adequate if you know almost nothing about the topic. Self-regulation applied to an empty schema produces confident students who are monitoring nothing.",
        "how": [
            "Establish the knowledge base before introducing the strategy.",
            "Check the base is secure with retrieval, not with self-report.",
            "Teach the strategy inside the content rather than in a separate session.",
            "Expect strategy use to be weaker in unfamiliar topics, and reteach it there.",
        ],
        "tech": "A retrieval starter checks the base is actually present before you build regulation on top of it.",
        "watch": "Generic study skills lessons detached from subject content are the classic version of this error, and they transfer poorly.",
    },
    "03": {
        "what": "Before starting, break the task down: what is it actually asking, what does it require, which prior learning does it draw on?",
        "why": "Zimmerman's research on self-regulated learners found that task analysis distinguishes strong performers from weak ones at the outset. Weak performers begin writing; strong performers spend the first minute working out what the question wants. The difference in output is largely decided before either has written a sentence.",
        "how": [
            "Give a minute of analysis time before any work begins.",
            "Ask three questions: what is it asking, what will a good answer contain, what do I already know?",
            "Annotate the question itself rather than doing it mentally.",
            "Share a few analyses so students see how others read the question.",
        ],
        "tech": "Annotating the question on a shared board makes the analysis visible and collective, which is how students learn what a good analysis looks like.",
        "watch": "Task analysis that becomes a worksheet to complete stops being thinking and becomes another thing to finish before starting.",
    },
    "04": {
        "what": "Planning means choosing an approach deliberately rather than defaulting to whichever one you used last.",
        "why": "Flavell's work on metacognitive knowledge distinguishes knowing strategies from knowing when to use them. Students who have several methods available but never pause to select are functionally operating with one. Requiring the choice to be named, before work begins, makes the selection conscious and therefore improvable.",
        "how": [
            "Have students name the method they'll use and why, before they start.",
            "Keep a visible menu of the methods you've taught for this kind of problem.",
            "Ask two students who chose differently to explain their reasoning.",
            "Return at the end: was that the right choice?",
        ],
        "tech": "A strategy menu in a shared document, built up across a unit, gives students something to choose from rather than something to recall.",
        "watch": "If only one method has been taught properly, the choice is theatre. Build the repertoire before asking for selection.",
    },
    "05": {
        "what": "Build confidence on evidence of past success rather than on encouragement.",
        "why": "Zimmerman's work identifies self-efficacy as a driver of effort and persistence, and mastery experience as its most reliable source. Encouragement without evidence is unpersuasive to the student who has just failed twice. Pointing to a specific task they recently mastered gives them a concrete reason to expect they can do this one.",
        "how": [
            "Before a hard task, point to a comparable one they succeeded at.",
            "Be specific: three weeks ago you did this, and this is the same structure.",
            "Keep work accessible so past success can be revisited, not just remembered.",
            "Avoid general reassurance. You can do this is not evidence.",
        ],
        "tech": "A portfolio of prior work makes past success visible and revisitable, which is what turns it into evidence rather than a claim.",
        "watch": "Confidence built on tasks that were made easy collapses on contact with a real one, and the collapse costs more than the confidence gained.",
    },
    "06": {
        "what": "Pair every self-check with an external one. A student's sense of understanding isn't reliable evidence of understanding.",
        "why": "Winne's work on monitoring found that learners' internal judgements are systematically miscalibrated, particularly for novices, and particularly just after reading something. Fluency feels like knowledge. An external check, a quiz, a worked answer, a peer, converts a feeling into information.",
        "how": [
            "After any do you understand moment, follow with a question that tests it.",
            "Make the external check immediate, while the judgement is still fresh.",
            "Show students the gap when it appears, without making it a failure.",
            "Repeat often enough that they start distrusting the feeling themselves.",
        ],
        "tech": "A self-marking quiz with feedback gives the external check instantly and privately, which makes students more willing to find out they were wrong.",
        "watch": "Asking students to rate their own understanding and acting on the ratings alone builds a lesson on unreliable data.",
    },
    "07": {
        "what": "Provide a low-distraction environment while students are learning to monitor their own work, then withdraw the support as they take over.",
        "why": "Zimmerman's performance phase includes attention control as a component of self-regulation, and like the other components it's learned rather than innate. Scaffolding the environment first is legitimate; leaving the scaffold permanently isn't, because the student never develops the capacity themselves.",
        "how": [
            "Start with the structure: clear expectations, reduced distraction, defined work periods.",
            "Name what you're doing and why, so it's understood as temporary.",
            "Withdraw the external control in stages as students demonstrate they can manage.",
            "Expect regression and reinstate briefly rather than abandoning the fade.",
        ],
        "tech": "Classroom management tools can scaffold focus during the learning phase. Treat them as scaffolding to be removed, not as the permanent condition of the room.",
        "watch": "Monitoring software used indefinitely teaches compliance under observation rather than self-regulation, and students behave accordingly the moment it's off.",
    },
    "08": {
        "what": "Insert planned pauses during a task where students ask whether the approach is still working.",
        "why": "Winne's model treats monitoring as a process that fades without cues, particularly when a task is absorbing. The sunk cost problem is real: the further into a wrong method a student is, the less willing they're to abandon it. A checkpoint at the third minute is considerably cheaper than one at the twentieth.",
        "how": [
            "Plan two or three stop points into any extended task.",
            "At each, one question: is this working, and how do I know?",
            "Make changing approach explicitly acceptable at those points.",
            "Ask a couple of students what they changed and why.",
        ],
        "tech": "Timed checkpoint prompts on the board remove the need for you to interrupt, which makes the pause feel structural rather than like a correction.",
        "watch": "Checkpoints that always conclude carry on become ritual. Some students need to be given permission to abandon and restart.",
    },
    "09": {
        "what": "Teach students to interrupt themselves mid-task with a direct question: do I actually understand this, or am I just following along?",
        "why": "Flavell's original account of metacognition centres on this kind of monitoring during a cognitive activity. The value is timing. A gap noticed while there's still time to fix it becomes a question to the teacher; the same gap noticed in an exam becomes a lost mark. Students rarely do this unprompted because the prompt has to come from inside.",
        "how": [
            "Teach the specific question and the moments to ask it.",
            "Model it aloud yourself while working through an example.",
            "Give a physical cue, a margin mark, for I am not sure here.",
            "Follow up on the marks rather than only on the finished work.",
        ],
        "tech": "Self-check prompts embedded in a task give the interruption a home, though the aim is that students eventually generate it without one.",
        "watch": "Students who mark uncertainty and get no response stop marking it. The follow-up is what makes the honesty worth their while.",
    },
    "10": {
        "what": "Have students leave a visible trace of their reasoning as they work, so the process can be inspected rather than only the outcome.",
        "why": "Flavell's point that regulation you can't see you can't coach applies directly to teaching. A correct answer conceals whether the method was sound or lucky; a wrong answer conceals where the reasoning broke. The working is the diagnostic material, and it's also what students can review themselves later.",
        "how": [
            "Require working to be shown, including the rejected attempts.",
            "Ask for a sentence on why this method, not just the steps.",
            "Mark the process as well as the answer so the requirement is credible.",
            "Use strong examples of working as models for the class.",
        ],
        "tech": "A shared document or digital notebook keeps the working, which paper working rarely survives beyond the lesson.",
        "watch": "Demanding working while only rewarding answers teaches students that the working is a formality, and they'll produce it retrospectively.",
    },
    "11": {
        "what": "Self-evaluation needs a reference. Give students the mark scheme or an exemplar to judge their work against rather than asking how they think they did.",
        "why": "Zimmerman's self-reflection phase depends on self-judgement, and judgement requires a standard. Without one, students fall back on effort or on comparison with the person next to them, neither of which is a measure of quality. The reference turns a feeling into an assessment.",
        "how": [
            "Provide the standard before the self-evaluation, not after.",
            "Ask for evidence: which line meets this criterion?",
            "Require one specific gap to be named.",
            "Compare their judgement with yours and discuss the difference rather than overriding it.",
        ],
        "tech": "Showing the exemplar alongside their own work, on screen or on a split page, removes the memory load from the comparison.",
        "watch": "Self-evaluation against a standard students can't yet recognise produces confident inaccuracy. Teach the standard with exemplars first.",
    },
    "12": {
        "what": "Steer how students explain their results towards the method they used, which they can change, and away from fixed ability, which they can't.",
        "why": "Zimmerman's work on attribution within the self-reflection phase shows that causal explanations shape the next attempt. A student who attributes failure to being bad at this has no next step. A student who attributes it to not checking their working has an obvious one. The attribution is teachable and it determines whether effort continues.",
        "how": [
            "After results, ask what specifically produced that outcome.",
            "Push past I didn't revise enough to what revision was actually done.",
            "Name the method in your own feedback so the language is modelled.",
            "Challenge fixed-ability language when you hear it, gently and consistently.",
        ],
        "tech": "A structured reflection prompt after results keeps the focus on method rather than letting it drift to ability or luck.",
        "watch": "Attributing everything to effort is its own trap. A student who worked hard with a poor method needs a better method, not more hours.",
    },
    "13": {
        "what": "Every reflection ends with one concrete adjustment for the next task. Not a general resolution, a specific change.",
        "why": "Butler's model of feedback and self-regulation treats the loop as incomplete until the learner adapts their approach. Reflection that stops at insight changes nothing. The adjustment has to be small enough to actually happen and specific enough to be checked, which rules out most of what students write when asked to reflect.",
        "how": [
            "One adjustment, written, in the student's own words.",
            "Test it: could someone else tell whether you did it?",
            "Carry it forward to the next task explicitly.",
            "Start the next reflection by checking whether the previous adjustment happened.",
        ],
        "tech": "An action log carried between tasks makes the follow-through visible, which is what stops reflection becoming a ritual.",
        "watch": "I will try harder next time isn't an adjustment. It fails the test of whether anyone could tell if it happened.",
    },
    "14": {
        "what": "Students predict their mark before it's revealed, then compare. Over time the gap narrows.",
        "why": "Winne's research on calibration shows that accuracy in self-judgement improves with repeated feedback on the mismatch, and that calibration matters because it drives revision decisions. A student who thinks they know a topic won't revise it. Improving the accuracy of that judgement is often worth more than improving the knowledge directly.",
        "how": [
            "Prediction written before submission, not after.",
            "Reveal the actual mark and record both.",
            "Track the gap across a term rather than a single instance.",
            "Discuss the pattern: consistent overestimation means something different from random error.",
        ],
        "tech": "Logging predictions alongside marks in a spreadsheet or LMS makes the trend visible, which a single comparison can't be.",
        "watch": "Students who learn that low predictions look modest will game it. Make clear you are interested in accuracy, not humility.",
    },
    "15": {
        "what": "Use what students notice about their own errors to decide what you reteach. Their reflection feeds your planning.",
        "why": "Butler's account treats self-regulation and instruction as a loop rather than two separate systems. If student reflection never changes teaching, the loop is open and students learn that the reflection was for their benefit only, which reduces the care they put into it. Closing it makes the reflection consequential.",
        "how": [
            "Collect the common self-identified gaps after an assessment.",
            "Plan the next lesson from those rather than from your own analysis alone.",
            "Tell the class where the lesson came from.",
            "Compare their analysis with yours and discuss where they differ.",
        ],
        "tech": "An exit poll of common errors gives you the class picture in two minutes, which is what makes acting on it realistic.",
        "watch": "Where student self-diagnosis is inaccurate, teaching only to it entrenches the misconception. Their analysis informs yours; it does not replace it.",
    },
    "16": {
        "what": "Teach the strategies themselves as named methods: retrieval practice, spacing, self-explanation, elaboration. Students cannot deploy what they have never been taught.",
        "why": "Flavell's category of metacognitive knowledge includes knowledge of strategies, and it's knowledge like any other: it has to be taught. Students left to discover study methods overwhelmingly arrive at rereading and highlighting, because those are the most obvious and the least effortful.",
        "how": [
            "Name each strategy explicitly when you use it in class.",
            "Explain what it's, what it's for, and why it works.",
            "Practise it in lesson before expecting it in independent study.",
            "Keep a running reference of the strategies the class has been taught.",
        ],
        "tech": "A strategy reference sheet, built up over the year and kept accessible, means the repertoire is available at the point of revision.",
        "watch": "A single assembly on study skills isn't teaching the strategies. They need practising in the subject with the subject's content.",
    },
    "17": {
        "what": "Beyond knowing a strategy, students need to know when it applies. That's conditional knowledge, and it's the harder half.",
        "why": "Winne identifies conditional knowledge, knowing which approach suits which situation, as a key discriminator between skilled and unskilled learners. A student with five strategies and no sense of when to use each isn't much better off than a student with one. The cues that signal which method fits have to be taught explicitly.",
        "how": [
            "Teach the cues alongside the strategy: use this when the task looks like this.",
            "Give sorting activities: here are six tasks, which method suits each?",
            "Discuss the near misses, where two methods could apply.",
            "Ask students to justify the match, not just make it.",
        ],
        "tech": "Worked cases matched to methods, kept as a reference, give students examples to reason from rather than rules to recall.",
        "watch": "Teaching the strategy thoroughly and the conditions not at all is the most common version of this gap, and it looks like successful teaching right up until transfer is required.",
    },
    "18": {
        "what": "Move from modelled to guided to independent use, removing prompts as students show they no longer need them.",
        "why": "Zimmerman's model of developing self-regulation runs through observation, emulation, self-control and self-regulation. The support has to be withdrawn for the final stage to exist at all. Fading isn't a nicety at the end of a sequence; it's the mechanism by which regulation transfers from the teacher to the learner.",
        "how": [
            "Model the strategy fully first, thinking aloud.",
            "Guide the next attempt with prompts.",
            "Reduce the prompts to a checklist, then a reminder, then nothing.",
            "Fade in response to evidence rather than to the calendar.",
        ],
        "tech": "Prompts embedded in a template can be removed version by version, which makes the fading concrete rather than a matter of your restraint.",
        "watch": "The scaffold that stays because removing it makes results dip is the scaffold most in need of removing. The dip is the point at which the learning starts.",
    },
    "19": {
        "what": "Students trial a study method, judge it against their actual results, and keep only what the evidence supports.",
        "why": "Winne's model of self-regulated learning is adaptive: the learner evaluates the effectiveness of an approach and revises it. Most students never do this, so ineffective methods persist for years because they were never tested. Running the test explicitly, once, changes revision behaviour more than being told what works.",
        "how": [
            "Have students name the method they'll use for the next assessment.",
            "Log it before, not after.",
            "Compare method and outcome afterwards, honestly.",
            "Decide together what to keep and what to drop for next time.",
        ],
        "tech": "A method log kept alongside results makes the comparison possible. Without a record, students reconstruct what they did and reconstruct it flatteringly.",
        "watch": "One data point is not evidence. A poor result with a good method can have other causes, and abandoning the method would be the wrong lesson.",
    },
    "20": {
        "what": "Teach each strategy inside the content it serves rather than in a standalone session about learning.",
        "why": "Willingham's consistent argument is that strategies don't float free of subject knowledge, and that transfer between domains is much weaker than we assume. A student who has learned to self-explain in science won't automatically do so in history. Teaching the strategy in each subject, with that subject's content, is the only reliable route.",
        "how": [
            "Teach the strategy in your subject, with your content.",
            "Show what it looks like specifically here, since it will differ by subject.",
            "Do not assume transfer from another subject's teaching of the same strategy.",
            "Coordinate across subjects on language, not on delivery.",
        ],
        "tech": "Subject-specific strategy banks keep the examples grounded in the content students are actually working on.",
        "watch": "A whole-school metacognition programme delivered in tutor time, with no subject follow-through, is the reliable way to get very little from a good idea.",
    },
    "21": {
        "what": "Teach students to schedule their own returns to a topic, rather than waiting to be told when to review.",
        "why": "Deciding when to study is a planning act and therefore part of self-regulation, not just of memory. Zimmerman's forethought phase includes time management explicitly. Handing the scheduling to students, once they understand spacing, moves the responsibility to where it will need to sit permanently.",
        "how": [
            "Teach spacing first so the schedule makes sense.",
            "Have students set their own reminders in front of you the first time.",
            "Ask for the intervals they chose and why.",
            "Follow up: did the reminder fire, and did you act on it?",
        ],
        "tech": "Calendar reminders on whatever device they already carry. The tool matters far less than whether they set it themselves.",
        "watch": "Reminders set once and ignored thereafter are worse than none, because students conclude the technique doesn't work for them.",
    },
    "22": {
        "what": "Students build their own quizzes and flashcards from their own notes, rather than using ready-made sets.",
        "why": "Writing a good question means deciding what's worth asking, which is a metacognitive act in itself. Winne's emphasis on learner-generated monitoring applies directly: a self-built quiz reflects the student's own model of the topic, including its gaps, and building it surfaces those gaps before any answering happens.",
        "how": [
            "Require questions to be written from their own notes, not from the textbook.",
            "Specify a mix of question types so it isn't all recall.",
            "Have them write the answers separately, so the questions can be used properly.",
            "Swap decks with a partner to test whether the questions are answerable.",
        ],
        "tech": "Flashcard apps with self-built decks combine the authoring benefit with automatic spacing, which is a rare case of a tool serving both.",
        "watch": "Downloaded decks skip the authoring, which is where most of the value is. The convenience is exactly what removes the learning.",
    },
    "23": {
        "what": "Self-regulation now includes managing the device. Teach students to use focus modes and silence notifications as a deliberate choice.",
        "why": "Attention control is part of Zimmerman's performance phase, and the modern version of it is largely about the screen in front of the learner. Treating device management as a rule imposed by adults produces compliance while supervised. Treating it as a strategy the learner deploys produces something that survives into independent study.",
        "how": [
            "Teach the specific settings rather than telling students to concentrate.",
            "Have them set focus mode at the start of independent work, themselves.",
            "Discuss what they notice about their own attention with and without it.",
            "Frame it as a technique they own, not a restriction you impose.",
        ],
        "tech": "Focus modes and app limits exist on every platform students use. Most have never been shown where they are.",
        "watch": "Blocking imposed entirely from outside teaches nothing about self-regulation, and students become skilled at circumventing it rather than at managing attention.",
    },
    "24": {
        "what": "Use AI to check and challenge reasoning that the student has already done, not to produce the reasoning in the first place.",
        "why": "Willingham's formulation that memory is the residue of thought is the whole argument in one line. Whatever the student thinks about is what they'll remember. If the model does the thinking, the model has the residue and the student has a document. Used as a critic of work already produced, it can prompt thinking the student wouldn't otherwise have done.",
        "how": [
            "Require the student's own attempt first, and keep it.",
            "Ask the model to critique or question rather than to improve or rewrite.",
            "Have students evaluate the critique. Some of it will be wrong.",
            "Compare the before and after, and discuss what actually changed and why.",
        ],
        "tech": "Any general assistant can play this role. What counts is the instruction you give it and the order you do things in, not which tool you pick.",
        "watch": "A tool that produces a better piece of work hasn't necessarily produced any learning. The question is always what thinking the student did.",
    },
}
