# -*- coding: utf-8 -*-
"""
Chapter 01 — Retrieval Practice.
Expansions for each of the 24 strategies on the infographic.

Keys map to the strategy number as printed on the card.
Each entry: what it is, why it works, how to run it, where technology
serves, and the failure mode to watch for.
"""

EXPANSIONS = {
    "01": {
        "what": "Retrieval means getting knowledge out of memory rather than putting it in again. In practice it is the difference between a class rereading their notes on the water cycle and a class closing their books and writing down everything they can remember about it. The second one looks less productive and does considerably more.",
        "why": "Roediger and Karpicke gave students the same material and the same amount of study time, then split them: one group restudied, the other was tested. On an immediate test the restudy group looked better. A week later the tested group remembered far more. The act of retrieving strengthens the memory trace in a way that reviewing does not, which is why the effect is called the testing effect even though no assessment is involved.",
        "how": [
            "Pick the point in the lesson where you would normally say \"read over that again\" and replace it.",
            "Books closed, screens down. Ask for everything they can remember about the topic, in whatever form suits: prose, bullets, a labelled sketch.",
            "Give it two or three minutes. The silence will feel long. Hold it.",
            "Only then let them open books to check and correct in a different colour.",
            "Scan a few. What is missing across the room is what you reteach.",
        ],
        "tech": "A quizzing or flashcard tool lowers the cost of doing this every lesson, because nothing needs marking. What technology must not do is supply the answer before the effort has happened. If your tool shows a hint by default, turn it off.",
        "watch": "Retrieval with notes open is reading. If students can see the material while they answer, you have replaced the difficulty that makes this work with the comfort that undoes it.",
    },
    "02": {
        "what": "Five questions at the start of every lesson, all of them on content you taught before today, and none of them recorded as a grade. It takes four minutes and it is the single easiest way to get retrieval into a scheme of work without redesigning anything.",
        "why": "Agarwal's classroom studies found that routine low-stakes quizzing reduced test anxiety rather than adding to it. When quizzing is normal, frequent and carries no weight, the stakes drain out of it. Students also arrive expecting to think, which changes the first four minutes of a lesson considerably.",
        "how": [
            "Write five questions from previous lessons, not today's.",
            "Display them as students come in so the routine starts without you.",
            "Answers on whiteboards or in the back of books. Nothing goes in the gradebook.",
            "Go through them briskly, correcting misconceptions as you meet them.",
            "Note anything most of the class missed. That is your reteaching list.",
        ],
        "tech": "A quiz or response tool gives you the spread of answers instantly, which is worth more than the score. Question banks let you reuse and reshuffle so writing five questions stops being a weekly chore.",
        "watch": "The moment it counts towards a grade, it stops being low stakes and students start revising for it the night before. That is a different activity with different effects.",
    },
    "03": {
        "what": "A blank page, two minutes, no notes: write down everything you remember about this topic. No structure imposed, no marks, no right way to lay it out. It is the purest form of free recall available in a classroom.",
        "why": "The value sits in the gaps. What a class cannot produce without prompting is a precise map of where your teaching needs to return, and it is far more honest than asking whether everyone understood. The effortful, incomplete attempt is doing the work; the tidy version they could copy would not.",
        "how": [
            "Name the topic and the time limit. Two minutes is usually enough.",
            "Books closed. Make clear that a messy, partial answer is the expected outcome.",
            "When time is up, let them add to their own page in a second colour from memory prompts you give aloud.",
            "Then open books and correct in a third colour.",
            "Collect five at random. The pattern across five tells you most of what you need.",
        ],
        "tech": "A shared document or whiteboard tool works well when you want the class to see the collective picture build up. Individual recall first though, always, or the confident few will do the remembering for everyone.",
        "watch": "Turning it into a competition for who wrote most rewards fast writers rather than secure knowledge, and it quietly punishes anyone who finds writing effortful.",
    },
    "04": {
        "what": "Quiz the class on material you have not taught yet. They will get most of it wrong, which is the point. The failed attempt primes them for the teaching that follows.",
        "why": "Bjork's work on desirable difficulties and Kapur's on productive failure both point the same way: struggling to retrieve something you do not yet know improves how well you remember it once you are told. The brain that has just searched for an answer and come up empty is markedly better prepared to receive that answer than the brain that has not.",
        "how": [
            "Write four or five questions on the content of today's lesson.",
            "Set them before any teaching, and say plainly that you expect them not to know most of it.",
            "Let them attempt everything. Guessing is fine. Blank is not.",
            "Teach the lesson.",
            "Return to the same questions at the end so they can see the shift.",
        ],
        "tech": "A pre-lesson quiz tool makes this a two-minute routine rather than a printing job, and lets you compare the before and after picture without marking anything.",
        "watch": "If students think the pre-test counts for something, the failure becomes threatening rather than productive. Be explicit that getting it wrong now is exactly what is supposed to happen.",
    },
    "05": {
        "what": "Students reconstruct the key ideas of a topic from memory, then open their notes and correct what they wrote in a different colour. The corrections become the record of what to revisit.",
        "why": "Karpicke and Blunt found that retrieval-based reconstruction beat elaborative study for later retention, including on questions requiring inference rather than recall. Writing it out from memory forces you to organise the knowledge, and organising is where the learning happens. The second colour then makes the gap visible to both of you.",
        "how": [
            "Give a clear scope: this topic, these ideas, roughly this much.",
            "Closed book reconstruction first, in their usual pen.",
            "Notes open, corrections and additions in a contrasting colour.",
            "Ask them to circle the single thing they most need to revisit.",
            "Next lesson, start with those circled items.",
        ],
        "tech": "A document tool with colour annotation keeps the two passes visually distinct and makes the work easy to return to weeks later, which paper versions rarely are.",
        "watch": "If they copy rather than reconstruct, you have a transcription exercise. Watch for books that open too early and for reconstructions that match the notes suspiciously closely.",
    },
    "06": {
        "what": "Spread retrieval across days and weeks rather than concentrating it in one session. The same total practice time, distributed differently, produces substantially better retention.",
        "why": "Ebbinghaus mapped the forgetting curve in the 1880s and Cepeda's meta-analysis confirmed the practical consequence: material revisited at intervals is retained far longer than material studied once in a block. The gap is not wasted time. Some forgetting between attempts is what makes the next retrieval effortful, and the effort is what consolidates.",
        "how": [
            "When you plan a unit, mark the review points before you plan the lessons.",
            "Aim to return to significant content at widening intervals: a few days, then a couple of weeks, then a month.",
            "Keep each return short. Three questions is plenty.",
            "Protect those slots when the scheme of work gets tight, because they are the bit that makes the rest stick.",
        ],
        "tech": "Spaced repetition tools schedule the return automatically, which is precisely the admin that otherwise makes spacing collapse under pressure. Let the tool own the calendar; keep the thinking with the student.",
        "watch": "Spacing gets cut first when you are behind. That feels like efficiency and is the opposite, because blocked teaching produces confident students who cannot retrieve the material in June.",
    },
    "07": {
        "what": "Three questions at the start of a lesson: one on yesterday's content, one on last week's, one on last month's. It is the simplest possible implementation of spacing and it fits in five minutes.",
        "why": "Rosenshine's principles put daily review at the top for good reason, and Bjork's spacing research explains why the three different intervals matter. Yesterday's question checks consolidation, last week's checks retention, last month's checks whether it has made it into long-term memory at all. The three together tell you more than any one of them.",
        "how": [
            "Build the three-question slide into your lesson template so it is always there.",
            "Draw the questions from your own scheme of work, not a generic bank.",
            "Whiteboards up, so you see the whole room rather than the one who volunteers.",
            "Adjust the intervals for difficulty. Genuinely hard content needs revisiting sooner than a month.",
        ],
        "tech": "A quiz tool or a lesson slide template makes this repeatable. The template matters more than the tool, because what kills the routine is having to invent it every morning.",
        "watch": "The intervals are a starting point, not a rule. If last month's question comes back blank across the room, the content needed revisiting three weeks ago.",
    },
    "08": {
        "what": "Mix question types and topics within a practice session rather than finishing one type before starting the next. Instead of twenty questions on one method, give twenty that switch between three.",
        "why": "Kornell and Bjork, and Rohrer's work in mathematics, found that interleaved practice produces stronger long-term performance than blocked practice, even though it feels worse during the session. Blocking lets students apply a method without deciding which method applies. Interleaving forces the discrimination, and discriminating is most of what an exam question actually asks for.",
        "how": [
            "Take a worksheet that runs through one method and reorder it so types alternate.",
            "Warn the class that this will feel harder and slower than usual. It will.",
            "Expect performance in the session to dip. That is not a sign it is failing.",
            "Compare on a delayed test rather than an immediate one.",
        ],
        "tech": "A shuffled quiz or random question tool does the interleaving for you, and removes the temptation to group similar questions together for tidiness.",
        "watch": "Interleaving needs secure foundations first. Mix topics before the individual methods are understood and you get confusion rather than discrimination.",
    },
    "09": {
        "what": "Teach students the schedule itself: study it, come back after two days, then after a week, then after a month. Most students do the opposite, which is to reread everything the night before.",
        "why": "Dunlosky's review of ten common study techniques rated practice testing and distributed practice as the two with the strongest evidence, and rated rereading and highlighting near the bottom. Students overwhelmingly use the bottom two, because those feel fluent. Showing them the ranking is often the intervention.",
        "how": [
            "Show the class the actual evidence on which techniques work. They find it genuinely surprising.",
            "Give them a concrete schedule rather than advice to space it out.",
            "Model it for one topic so they see what a two-day return looks like in practice.",
            "Ask them to plan the next fortnight's returns for one subject, then hold them to it.",
        ],
        "tech": "Spaced repetition apps and revision planners make the schedule self-running. The teaching is in the first conversation about why the schedule looks like that.",
        "watch": "Telling students to space their revision without showing them what it looks like on a calendar produces agreement and no change in behaviour.",
    },
    "10": {
        "what": "Build earlier content back into starters, homework and assessments across the year, so nothing is finished the moment the unit ends.",
        "why": "Bjork's work on spacing, and the practical point Benedict Carey makes well, is that memory needs repeated retrieval at intervals to stay accessible. There is also a signalling effect worth taking seriously: when content never reappears, students correctly infer that it no longer matters, and they stop maintaining it.",
        "how": [
            "Write your medium-term plan with cumulative review built in, not appended.",
            "Every assessment includes questions from earlier units, not just the current one.",
            "Make the cumulative nature explicit so students know old content stays live.",
            "Keep a running question bank per unit so pulling old material back is quick.",
        ],
        "tech": "A question bank or quiz builder with tagging by unit makes cumulative assessment a filtering job rather than a writing job.",
        "watch": "Cumulative review that only ever appears in the final exam is not cumulative review. It has to show up in ordinary weeks to change what students maintain.",
    },
    "11": {
        "what": "Choose the version of a task that feels harder in the lesson when the evidence says it retains better. Effortful retrieval is the clearest example, but so are spacing, interleaving and reduced scaffolding.",
        "why": "Bjork coined desirable difficulties for exactly this: conditions that slow apparent learning during instruction but improve retention and transfer afterwards. The uncomfortable part is that fluency during a lesson is a poor guide to learning, and both teachers and students read it as a good one.",
        "how": [
            "Notice where you have made something easier out of kindness and ask whether it removed the thinking.",
            "Delay the hint. Count to five before you offer it.",
            "Let a struggle run a little longer than is comfortable before you intervene.",
            "Explain to the class why the lesson feels harder, so it does not read as poor teaching.",
        ],
        "tech": "Any retrieval tool works, with hints and multiple-choice options disabled. The default settings on most platforms are tuned for engagement, not for difficulty.",
        "watch": "Desirable is doing real work in that phrase. Difficulty that a student has no route through is just difficulty, and it teaches them that the subject is not for them.",
    },
    "12": {
        "what": "Fade the support across a sequence: full notes available, then headings only, then nothing. The transition to unaided retrieval is where the consolidation happens.",
        "why": "Bjork and Kornell's work on scaffolding and retrieval shows that support which is never withdrawn produces performance that collapses the moment it is removed. Fading is not a nicety at the end; it is the mechanism by which the student takes over.",
        "how": [
            "Plan three passes over the content with decreasing support.",
            "Pass one: notes available, focus on getting the shape right.",
            "Pass two: headings or a skeleton only.",
            "Pass three: blank page.",
            "Be explicit that the third pass is the one that counts for their own judgement of what they know.",
        ],
        "tech": "A quiz tool with a closed-book or timed mode enforces the final pass in a way that trusting to willpower does not.",
        "watch": "Fading only works if you actually do it. Scaffolds have a habit of becoming permanent because removing them makes the class look less successful for a week.",
    },
    "13": {
        "what": "Retrieve the same knowledge in different formats and settings: written one week, spoken the next, as a diagram the week after, in a different room or a different order.",
        "why": "Godden and Baddeley's divers famously recalled better in the environment where they learned, which tells you memory picks up contextual cues you did not intend to teach. Varying the context decontextualises the knowledge, so it is not welded to one format, one room or one question style. It is harder for students, and that is precisely the point.",
        "how": [
            "Rotate the format of your recall activities rather than settling on a favourite.",
            "Ask for the same content as prose, as a diagram, as an explanation to a partner.",
            "Occasionally change where or when the retrieval happens.",
            "Vary the question wording so recall is not tied to a phrasing.",
        ],
        "tech": "Multi-modal tools let you switch format without rebuilding the activity each time: the same content as a quiz, a mind map, a voice note.",
        "watch": "Variety for its own sake becomes novelty-chasing. The variation has to be in how the knowledge is retrieved, not in how entertaining the packaging is.",
    },
    "14": {
        "what": "Have students produce an answer before they are given it, even when you know the answer will be wrong. Generating beats being told, and generating badly still beats being told.",
        "why": "Slamecka and Graf's generation effect showed that words a participant produced were remembered better than words they read, and McDaniel's later work extended it to classroom material. The effort of generation is what drives the encoding. Accuracy is close to irrelevant at that moment.",
        "how": [
            "Before defining a term, ask what they think it might mean.",
            "Before giving the method, ask how they would approach it.",
            "Take a few answers without correcting them yet.",
            "Then teach, and explicitly connect back to what they guessed.",
        ],
        "tech": "A response tool captures every student's guess rather than the three you have time to hear, and lets you show the spread of thinking before you resolve it.",
        "watch": "If wrong guesses get visibly corrected in front of the class in a way that stings, students learn to stay quiet, and the generation stops happening.",
    },
    "15": {
        "what": "Do not test immediately after teaching. Wait a day, then quiz. Wait a week, then quiz again. The gap is not a delay before the learning; it is part of it.",
        "why": "Retrieval immediately after instruction is easy because the material is still in working memory, and easy retrieval strengthens little. Bjork's storage and retrieval strength distinction explains it: you need retrieval strength to have dropped somewhat for the act of retrieving to do useful work. Some forgetting is a precondition.",
        "how": [
            "Resist the end-of-lesson quiz on today's content as a measure of learning. Use it as a check of attention instead.",
            "Put the real retrieval a lesson or two later.",
            "Make the delay explicit to students so the difficulty is expected.",
            "Track which items need shorter gaps because they keep coming back blank.",
        ],
        "tech": "A spaced quiz tool handles the delay for you. Without one, the intention to come back in three days rarely survives contact with a busy week.",
        "watch": "An immediate end-of-lesson quiz that everybody passes is reassuring and tells you almost nothing about what will still be there in a fortnight.",
    },
    "16": {
        "what": "Retrieval is not only for facts. Once the factual base is secure, retrieve explanations, comparisons, causes and applications too.",
        "why": "Agarwal's work found that higher-order retrieval practice supported higher-order performance, and that factual retrieval alone did not automatically transfer. The factual layer builds the schema you need; the higher-order questions test whether the student can use it. Both matter, and in that order.",
        "how": [
            "Start a topic with factual recall to secure the foundations.",
            "Move to why and how questions once the facts are reliable.",
            "Ask for comparisons and connections between topics, not just within one.",
            "Keep both types running rather than graduating away from facts entirely.",
        ],
        "tech": "A quiz tool with varied question types, including short written responses, stops the routine collapsing into multiple choice by default.",
        "watch": "Retrieval practice that never leaves the factual layer produces students who can name everything and explain nothing. The reverse, jumping to analysis on shaky foundations, fails differently and just as reliably.",
    },
    "17": {
        "what": "Students draw a concept map of a topic from memory, showing not just the ideas but how they connect. Notes stay closed until the map is done.",
        "why": "Karpicke and Blunt compared concept mapping while studying against retrieval practice, and found retrieval won. Mapping from memory combines both: it is a retrieval task that happens to produce a map. What it surfaces that a list does not is relational knowledge, whether the student can see how the parts hang together.",
        "how": [
            "Give the topic and, at most, a handful of anchor terms.",
            "Closed book. The map is built from memory.",
            "Insist on labelled links, not just lines. The label is where the thinking shows.",
            "Compare against notes afterwards and add missing connections in another colour.",
        ],
        "tech": "A mind-mapping or diagram tool makes maps easy to revise and revisit, which matters if you want students to return to the same map later in the year and extend it.",
        "watch": "A beautiful map with unlabelled arrows tells you very little. The relationships are the content; the layout is not.",
    },
    "18": {
        "what": "Have students prepare to teach a topic to someone else. The learning happens in the preparation, whether or not the teaching ever takes place.",
        "why": "Nestojko and colleagues found that simply expecting to teach material changed how people studied it and improved recall, compared with expecting to be tested. Fiorella and Mayer's work on learning by teaching points the same way. Preparing to explain forces complete, organised retrieval in a way that answering questions does not.",
        "how": [
            "Assign a sub-topic each and set the expectation of teaching it.",
            "Insist on preparation from memory first, notes second.",
            "Require a worked example, not just an explanation.",
            "The delivery can be to a partner, to a camera, or not at all. The preparation is the bit that counts.",
        ],
        "tech": "A video recording or presentation tool gives the preparation a real audience and produces a revision artefact the class can return to.",
        "watch": "If students prepare by copying from the textbook, no retrieval has occurred. Set the preparation as a closed-book task first.",
    },
    "19": {
        "what": "Retrieval supported by a cue: a heading, a first letter, a keyword, a diagram with the labels removed. It triggers the search without doing the searching.",
        "why": "Tulving and Thomson's encoding specificity principle established that what you can retrieve depends heavily on the cues available. Cued recall sits usefully between multiple choice, which offers too much, and free recall, which can be overwhelming for students who are not yet secure. It builds confidence on the way to unaided retrieval.",
        "how": [
            "Use cued recall early in a sequence and free recall later.",
            "Cues can be structural: headings, a numbered skeleton, a stripped diagram.",
            "Reduce the cues each time the class returns to the topic.",
            "Be clear with students that the cues are temporary.",
        ],
        "tech": "Cloze exercises and gapped handouts generate quickly from existing notes, and a digital version makes reducing the cues on the next pass a two-minute edit.",
        "watch": "Cues that give away the answer are not cues. If the gap can be filled from the surrounding sentence without knowing the content, nothing has been retrieved.",
    },
    "20": {
        "what": "Show students the difference between feeling like they know something and actually knowing it. Ask for a confidence rating before the answer is revealed, then let them see the mismatch.",
        "why": "Koriat and Bjork called it the illusion of knowing: fluency with material, usually from rereading it recently, gets mistaken for secure knowledge. Dunlosky's work found students consistently overestimate what they will remember. Confident and wrong is the most useful diagnostic state there is, because it is the one the student cannot detect alone.",
        "how": [
            "Ask for an answer and a confidence rating together, high, medium or low.",
            "Reveal the answer only afterwards.",
            "Focus the discussion on the high-confidence errors, not the low-confidence ones.",
            "Repeat over weeks so students see their calibration improve.",
        ],
        "tech": "A confidence-rated quiz tool captures both dimensions and lets you find the confidently wrong answers across the whole class rather than the few you happen to see.",
        "watch": "If confidence ratings feel like another thing being marked, students report the confidence they think you want. Keep it genuinely stakes-free.",
    },
    "21": {
        "what": "Reveal the correct answer quickly when a student was confident and wrong. Allow a longer gap when the retrieval was effortful and uncertain.",
        "why": "Metcalfe's work on the hypercorrection effect found that high-confidence errors are corrected especially well when feedback arrives promptly. The surprise does useful work. For low-confidence retrieval, an immediate answer can short-circuit the effort that was about to pay off, so the timing genuinely differs by case.",
        "how": [
            "For quick factual recall, reveal answers promptly.",
            "For harder reasoning, let the struggle run before you resolve it.",
            "Pay particular attention to answers given confidently and wrongly. Correct those clearly and immediately.",
            "Tell students why the timing varies, so the delay does not read as withholding.",
        ],
        "tech": "Quiz tools with an instant reveal suit the factual case. For the harder work, turn the instant reveal off; the default is rarely what you want.",
        "watch": "Blanket immediate feedback on everything feels responsive and quietly removes the productive struggle from the tasks that most needed it.",
    },
    "22": {
        "what": "Students rate how confident they are in each answer, then check. Over time the gap between confidence and accuracy narrows, which is a skill in itself.",
        "why": "Dunlosky and Metcalfe showed that students are most confident about material they have most recently read, which is a poor proxy for what they know. Calibration improves with repeated feedback on the mismatch. A well-calibrated student revises the right things; a poorly calibrated one revises what already feels comfortable.",
        "how": [
            "Two columns: the answer, and a confidence rating.",
            "Check answers, then look at the pattern rather than the score.",
            "Ask each student to name one thing they were sure about and wrong about.",
            "Return to those items specifically in the next round.",
        ],
        "tech": "Quiz tools with a confidence field make the pattern visible over time, which is where the value is. A single snapshot tells you much less than a term of them.",
        "watch": "Confidence ratings only help if students act on them. The rating is data; the revision decision is the point.",
    },
    "23": {
        "what": "A running log of what came back easily, what did not, and what needs revisiting. Kept by the student, not by you.",
        "why": "Zimmerman's self-regulation research found that students who monitor their own performance make better subsequent study decisions. The journal externalises the monitoring so it does not depend on memory or honesty in the moment. It also gives a student something concrete to work from in the week before an assessment, rather than a vague sense that they should look at everything.",
        "how": [
            "After each retrieval activity, three quick lines: solid, shaky, gone.",
            "Keep it in one place across the year rather than scattered through exercise books.",
            "Set revision from the shaky and gone columns, not from the start of the unit.",
            "Review the journal with them occasionally so it does not become a ritual.",
        ],
        "tech": "A learning journal or digital notebook keeps it searchable and stops it living in a book that gets left at home.",
        "watch": "Journals that are filled in because they are checked become fiction. The value depends on it being genuinely for the student.",
    },
    "24": {
        "what": "Ask students how they actually revise, then show them what the evidence says about those methods. The conversation is the intervention.",
        "why": "Dunlosky and colleagues rated ten study techniques by the strength of evidence behind them. Practice testing and distributed practice came out on top. Highlighting, summarising and rereading, which is what most students do, came out low. Students are not being lazy; they are using the strategies that feel most productive, and feeling productive is exactly what those strategies are good at.",
        "how": [
            "Survey the class anonymously on what they actually do.",
            "Show the ratings alongside their own results.",
            "Do not just tell them to stop rereading. Replace it with a specific alternative for a specific topic.",
            "Come back to it after the next assessment and ask what changed.",
        ],
        "tech": "A survey tool makes the anonymous audit quick and gives you a class picture worth showing back to them.",
        "watch": "One assembly on revision techniques changes very little. This needs to be revisited in the subject, with the subject's content, more than once.",
    },
}
