# -*- coding: utf-8 -*-
"""
Chapter 02 : Formative Assessment.
Expansions for each of the 24 strategies on the infographic.
"""

EXPANSIONS = {
    "01": {
        "what": "The learning intention is what students are meant to learn. The task is what they are meant to do. They aren't the same thing, and conflating them is one of the most common planning errors there's.",
        "why": "Wiliam's point is that students who are clear only about the task will optimise for completing it. Finish the poster, fill the sheet, get to question ten. None of that guarantees the learning. When the intention is stated separately, students have something to aim at beyond done, and you've something to assess against beyond finished.",
        "how": [
            "Write the intention and the task as two separate lines in your plan.",
            "Say both aloud: today we're learning X, and the way we'll do that's Y.",
            "When you circulate, ask about the intention rather than progress through the task.",
            "At the end, review against the intention, not against how far they got.",
        ],
        "tech": "Any display tool will do. The trick is keeping both lines visible all lesson, rather than flashing them up at the start and then replacing them with the instructions.",
        "watch": "Objectives copied into books at the start of a lesson are task compliance dressed as clarity. Nobody has yet learned anything by transcribing an aim.",
    },
    "02": {
        "what": "Rather than handing out success criteria, build them with the class before they begin: what would a good one of these actually look like?",
        "why": "Wiliam and Leahy found that criteria students have articulated themselves carry far more weight than criteria they've been given. The reason is straightforward. Generating the criteria requires you to think about quality; receiving them requires you to read. The wording they produce is also the wording they'll recognise later in feedback.",
        "how": [
            "Show one or two examples of the kind of work you want, ideally at different standards.",
            "Ask what makes the better one better. Collect their language, not yours.",
            "Shape their list into four or five criteria without silently replacing their words.",
            "Display the co-constructed version and refer to it by their phrasing all lesson.",
        ],
        "tech": "A collaborative document lets the whole class contribute rather than the four who speak, and the criteria stay editable as understanding develops.",
        "watch": "Asking for their criteria and then presenting yours anyway teaches them that the consultation is decorative, and they'll contribute less next time.",
    },
    "03": {
        "what": "Show real examples of work at different standards before students start their own, and let them work out what separates them. Exemplars first, rubric second.",
        "why": "Sadler argued that students can't close a gap they can't see, and Berger's work on models and critique shows how quickly quality becomes concrete when it's in front of you. A rubric describes quality in the abstract; an exemplar demonstrates it. Students are also markedly better at spotting strengths and weaknesses in someone else's work than in their own.",
        "how": [
            "Collect examples at three standards, anonymised or from previous years.",
            "Show the strongest last, not first, so the discussion builds.",
            "Ask what specifically makes the difference, pushing past it's neater or longer.",
            "Only then hand out the rubric, and connect each line to what they just saw.",
        ],
        "tech": "A visualiser puts real student work on the board in seconds without a scanning and printing detour, which is usually what stops this happening.",
        "watch": "Only ever showing excellent examples leaves students with no sense of the distance between standards, which is exactly the judgement you're trying to build.",
    },
    "04": {
        "what": "Do not give the objective at the start. Ask students at the end to say what they've learned, in their own words.",
        "why": "Generating an answer produces stronger memory than reading one, which is the same generation effect that makes retrieval practice work. There's a diagnostic bonus too: what a class says it has learned, unprompted, is a considerably more honest account of the lesson than a copied objective and a thumbs up.",
        "how": [
            "Plan the lesson so the intention becomes apparent through the work.",
            "In the last five minutes, ask for the learning in one sentence, written not spoken.",
            "Collect a sample and read them before the next lesson.",
            "Where the sentences drift from your intention, that's your starting point next time.",
        ],
        "tech": "A polling or whole-class response tool captures every sentence rather than the handful you can hear, and takes about ninety seconds.",
        "watch": "This works when the lesson is well structured. Withholding the objective from a lesson that lacks a clear line of sight just produces confusion.",
    },
    "05": {
        "what": "A hinge question sits at the turning point of a lesson. It's a single diagnostic question whose answers tell you whether to move on or go back, and it's written in advance.",
        "why": "Wiliam's design constraints are demanding on purpose: every student answers it in under a minute, you can interpret the responses in under thirty seconds, and each wrong answer maps to a specific misconception. Met properly, it converts a vague sense that they're with me into evidence you can act on immediately.",
        "how": [
            "Identify the point in the lesson where continuing without understanding would be wasteful.",
            "Write the question, and write what each wrong answer would tell you.",
            "Take every student's response at once, not hands up.",
            "Decide there and then: move on, reteach to all, or address one group.",
        ],
        "tech": "A polling or quiz tool gives you the distribution instantly, which is what makes the thirty-second interpretation realistic.",
        "watch": "Improvised hinge questions almost never have diagnostic distractors, so they tell you the proportion right and nothing about why the rest are wrong.",
    },
    "06": {
        "what": "Engineer the wrong answers in a multiple-choice question as carefully as the right one, so each distractor corresponds to a real misconception.",
        "why": "Wiliam and Black's point is that the value of a question lies in what the wrong answers tell you. A question with three obviously silly options measures whether students are paying attention. A question where every option is what a particular misunderstanding would produce turns a class response into a diagnosis.",
        "how": [
            "List the misconceptions you actually see in this topic. Your own marking is the best source.",
            "Write one distractor per misconception.",
            "Check that a student holding that misconception would confidently choose it.",
            "Look at the spread of answers, not the percentage correct.",
        ],
        "tech": "A quiz tool that shows the full response distribution, not just the score, is essential here. If you can only see how many got it right, the design work is wasted.",
        "watch": "Distractors that nobody picks are dead weight. If one option never gets chosen across a class, replace it with a misconception you actually meet.",
    },
    "07": {
        "what": "Decide who answers rather than taking whoever volunteers, and keep track so that nobody goes a fortnight without being asked.",
        "why": "Wiliam and Black's work on questioning shows that hands up systematically narrows participation to a confident minority, and that the rest of the class learns quickly that they can opt out. Deliberate selection, unlike random selection, also lets you target the student whose thinking you most need to hear at that moment.",
        "how": [
            "Establish the norm before you use it: I will ask anyone, and not knowing yet is fine.",
            "Keep a simple record of who has been asked and when.",
            "Choose deliberately when you need particular thinking, randomly when you want unpredictability.",
            "Allow thinking time between the question and the name.",
        ],
        "tech": "A participation tracking tool or a marked-up seating plan removes the memory burden, which is the reason most tracking systems stop after a fortnight.",
        "watch": "Cold calling without first building the climate for it lands as exposure rather than inclusion, and quiet students will disengage further.",
    },
    "08": {
        "what": "Every student writes an answer and holds it up at the same time. You read the room in seconds.",
        "why": "It's the fastest whole-class response method available and it works in every subject. Wiliam makes the case in terms of participation ratio: simultaneous responses mean every student has thought, not only the one who was asked. The simultaneity also matters, because it removes the chance to copy or to wait and see.",
        "how": [
            "Pose the question, give thinking time, then say show me.",
            "Scan the room before you comment on any individual answer.",
            "Respond to the pattern rather than to the first board you see.",
            "Keep it quick. Two or three rounds in a lesson, not twenty.",
        ],
        "tech": "Digital equivalents give you a record you can revisit, which physical boards don't. For speed and simplicity in the moment, the physical version is hard to beat.",
        "watch": "Waiting for the slowest writer every time turns a thirty-second check into a three-minute one. Keep the questions short enough to answer in a few words.",
    },
    "09": {
        "what": "Each student holds a set of lettered cards. You pose a multiple-choice question and everyone shows their answer at once.",
        "why": "It's mini whiteboards with less writing, which matters when the barrier is transcription speed rather than understanding. Paired with well-designed distractors, the spread of letters across the room is an instant map of which misconception is dominant, and Wiliam's case for it rests on exactly that diagnostic speed.",
        "how": [
            "Prepare questions with meaningful distractors in advance.",
            "Cards up on a count so nobody is following the room.",
            "Read the spread, then decide whether to reteach, discuss or move on.",
            "Where opinion is split, put students who disagree in conversation before you resolve it.",
        ],
        "tech": "An audience response tool does the same job with a record attached, and lets you compare the same question across classes or across the year.",
        "watch": "With four options, a quarter of the room can be right by accident. Follow up with why before you conclude the class has understood it.",
    },
    "10": {
        "what": "Offer more than one way to respond: written, spoken, drawn, digital. The method you pick decides who is able to show you what they know.",
        "why": "This is CAST's Universal Design for Learning principle of multiple means of action and expression applied to assessment. A student who understands the concept but struggles to write at speed will look, on a written response task, exactly like a student who doesn't understand. That is a measurement problem, not a learning one.",
        "how": [
            "Vary the response mode across a sequence rather than defaulting to writing.",
            "Where the mode isn't the thing being assessed, let students choose it.",
            "Offer an anonymous route for students who won't volunteer publicly.",
            "Check who is consistently invisible in your usual method, and change the method for them.",
        ],
        "tech": "Multimodal and anonymous response tools make this practical at speed. Without them, offering four routes usually means managing four sets of logistics.",
        "watch": "If the mode is what you're assessing, for example extended writing in English, then varying it changes the construct. Be clear which case you are in.",
    },
    "11": {
        "what": "Think alone, then discuss in pairs, then a nominated student reports back. All three stages, in that order, with the nomination made by you.",
        "why": "Wiliam's version is disciplined for a reason. Individual thinking first stops the confident partner doing the thinking for both. Nomination at the end, rather than volunteers, makes the report-back evidence rather than a performance by the willing. Skip either and the structure collapses into a chat.",
        "how": [
            "Individual thinking, silent, with a visible timer.",
            "Paired discussion with a specific task: agree, or find the difference between your answers.",
            "Nominate the reporter, and make clear from the start that anyone might be asked.",
            "Ask for the pair's answer, not the individual's, so the reporting is shared.",
        ],
        "tech": "A visible timer does more for this than any dedicated tool, because the discipline is entirely in the timings.",
        "watch": "Going straight to pairs is the most common shortcut and it wastes the technique. Without the individual stage, one student's first idea becomes the pair's answer.",
    },
    "12": {
        "what": "Return work in progress with comments and no grade attached.",
        "why": "Butler's study is the classic reference: students given comments alone improved, students given grades alone didn't, and students given both performed like the grades-only group. The grade appears to cancel the comment. Once there's a number, attention goes to the number and to how it compares with the person sitting next door.",
        "how": [
            "Decide in advance which pieces are formative. Those get comments only.",
            "Where grades are required by policy, record them separately and release them later.",
            "Give class time to read and respond before any grade appears.",
            "Tell students why you're doing it, or the missing grade reads as an oversight.",
        ],
        "tech": "An LMS or annotation tool that lets you withhold a grade until feedback has been actioned makes the delayed release practical rather than a paperwork exercise.",
        "watch": "If students can see the grade in the system while reading the comment, you've both conditions at once, and Butler's result says the comment loses.",
    },
    "13": {
        "what": "Feedback should require more work from the student than it did from you. Pose a question rather than writing the correction.",
        "why": "Wiliam's formulation is that feedback must cause thinking. If the response to a comment is to read it and nod, no learning event has occurred. Writing the improved sentence for a student is efficient for the marker and removes the cognitive work from precisely the person who needed to do it.",
        "how": [
            "Before writing a comment, ask what you want the student to do as a result.",
            "Phrase it so the doing is theirs: what evidence supports this, rather than add evidence here.",
            "Leave space and time for the response, in the book or the document.",
            "Check the responses. Unread responses train students not to bother.",
        ],
        "tech": "An annotation tool with a reply function turns feedback into a thread rather than a verdict, and makes the student's response visible in the same place.",
        "watch": "Questions that are really instructions in disguise, such as should you perhaps have included a conclusion, don't cause thinking. They cause compliance.",
    },
    "14": {
        "what": "Timetable the response. Start the next lesson with students reading and acting on feedback before anything new begins.",
        "why": "Wiliam and Leahy's point is blunt: feedback with no time to act on it's a gift to the filing system. The learning is in the response, not the receipt. Ten minutes at the start of a lesson is a small price for making the previous three hours of marking count for anything.",
        "how": [
            "Block the first ten minutes of the lesson after a marked piece. Every time.",
            "Give a specific task, not read my comments. Redraft this paragraph, or answer the three questions.",
            "Circulate and check the responses are real.",
            "Only then move on to new content.",
        ],
        "tech": "Sharing feedback through an LMS before the lesson means students arrive having already read it, and the ten minutes goes entirely on acting.",
        "watch": "Response time that gets squeezed whenever the curriculum is tight signals that the feedback was never the point. Protect it or stop writing the comments.",
    },
    "15": {
        "what": "Read the whole set, note the patterns, and teach to those. Common strengths, recurring errors, two or three next steps for the class.",
        "why": "Individual comments on thirty scripts take hours and repeat themselves substantially. Wiliam and Hattie both point towards feedback that changes teaching rather than annotating outcomes. Whole-class feedback is sustainable enough to survive a term, which is the quality that most marking policies lack.",
        "how": [
            "Read the set with a single sheet beside you: strengths, errors, misconceptions, next steps.",
            "Do not annotate as you read. Note only.",
            "Teach from the sheet at the start of the next lesson.",
            "Add individual comments only where a student's need is genuinely not on the sheet.",
        ],
        "tech": "A shared document or display tool means the class sees the same analysis you're working from, and can copy the next steps into their own work.",
        "watch": "Whole-class feedback used as a way to mark less, without the reteaching that follows, is just marking less.",
    },
    "16": {
        "what": "Return work with three questions rather than corrections. Students must answer them before moving on.",
        "why": "It's Wiliam's causes thinking principle made concrete and countable. Three is enough to matter and few enough that a class can genuinely respond to all of them in the time available. Corrections tell a student what was wrong; questions make them work out why, which is the part that transfers.",
        "how": [
            "Cap it at three per piece. Resist the urge to note everything.",
            "Make each one answerable in a sentence or two.",
            "Number them and leave numbered space for the responses.",
            "Read the responses, even briefly. That is what makes students take them seriously.",
        ],
        "tech": "Digital annotation with numbered comments keeps the questions and responses adjacent, which paper margins rarely manage.",
        "watch": "Three questions on a piece of work that needed one clear next step is scattergun. The number is a ceiling, not a target.",
    },
    "17": {
        "what": "Before students work alone, have them practise in structured steps with a partner, checking each other's responses at each stage.",
        "why": "Rosenshine's guided practice principle is that independence is the destination rather than the starting point, and that the highest-performing teachers spend longer in the guided phase than most. Peer checking at each step catches errors before they're practised into place, which is considerably cheaper than unpicking them later.",
        "how": [
            "Break the process into steps small enough to check.",
            "After each step, partners compare and resolve differences before continuing.",
            "Circulate and listen to the disagreements. They tell you where the teaching needs to return.",
            "Move to independent work only when the checks are coming back clean.",
        ],
        "tech": "A collaborative document lets you see several pairs working simultaneously, which is closer to circulating than looking over shoulders allows.",
        "watch": "Guided practice that never fades produces students who can do it together and not alone. Plan the withdrawal at the same time as the scaffold.",
    },
    "18": {
        "what": "Students write questions that could appear in an assessment on this topic. The best go into the class question bank.",
        "why": "Black and Wiliam's work on students as learning resources rests on the fact that generating a good question makes you decide what's worth asking about, which is a harder job than answering one. It also surfaces what students think the important content is, which isn't always what you think you taught.",
        "how": [
            "Specify the type: one recall, one explanation, one application.",
            "Ask for the answer alongside the question. It stops vague questions.",
            "Collect, select and use the best in the next starter, crediting the author.",
            "Discuss what makes a good question when the weak ones appear.",
        ],
        "tech": "A shared document or quiz builder means the class bank accumulates across the year rather than being lost in exercise books.",
        "watch": "Without a specified type you'll get twenty recall questions, because those are easiest to write and to answer.",
    },
    "19": {
        "what": "Peer assessment against shared criteria, with exemplars used first so that students know what quality looks like before they judge it.",
        "why": "Sadler's conditions apply to peers exactly as they do to teachers: you can't assess against a standard you can't yet recognise. Berger's critique protocols work because the standard is established first and the language for talking about it's taught. Skip that and peer feedback reduces to encouragement, which is pleasant and not useful.",
        "how": [
            "Establish the standard with exemplars before any peer work.",
            "Give a protocol: what to look for, in what order, in what words.",
            "Require evidence: point to the line that shows it.",
            "Model a critique yourself first, including how to say something isn't yet good enough.",
        ],
        "tech": "A peer assessment tool with the criteria embedded keeps students on the protocol rather than drifting into general comment.",
        "watch": "Peer feedback without shared criteria produces opinion. Well-meant opinion, delivered confidently, can send a student in entirely the wrong direction.",
    },
    "20": {
        "what": "Low-stakes quizzing on content from previous weeks and months, not today's lesson, returning at widening intervals.",
        "why": "Bjork's spacing research is among the most robust findings in the field. Material revisited at intervals is retained far longer than material studied in a block, and retrieving it's what does the work. Rereading notes produces fluency and very little retention, which is why students who revise that way are so often surprised in June.",
        "how": [
            "Quiz on prior content at the start of lessons as routine.",
            "Widen the intervals as material becomes secure.",
            "Keep it low stakes so the anxiety stays out of it.",
            "Track which items keep failing and shorten their interval.",
        ],
        "tech": "Spaced repetition tools schedule the returns automatically, which is the part that otherwise collapses when a term gets busy.",
        "watch": "Quizzing on today's content feels like retrieval practice and isn't. Today's material is still in working memory; retrieving it strengthens little.",
    },
    "21": {
        "what": "Quiz students on material before you teach it, so they experience not knowing before they're told.",
        "why": "Bjork's work on desirable difficulties and Wiliam's on activating prior knowledge converge here. The unsuccessful attempt primes attention: a student who has just failed to retrieve something is measurably better prepared to encode it when it arrives. The failure is doing work, provided it's framed as expected.",
        "how": [
            "Four or five questions on today's content, before any teaching.",
            "Say clearly that you expect them to get most of it wrong.",
            "Do not correct yet. Teach.",
            "Return to the same questions at the end and let them see the difference.",
        ],
        "tech": "A quiz tool at lesson start makes this routine rather than a printing job, and the before-and-after comparison is automatic.",
        "watch": "If it feels like a test with consequences, the productive failure becomes threatening and students disengage rather than engage.",
    },
    "22": {
        "what": "In the last two minutes, every student anonymously writes the one thing they're least clear about. You open the next lesson with the most common answers.",
        "why": "Angelo and Cross designed it as a classroom assessment technique and its value is the cost-benefit ratio: two minutes of lesson time for a ranked list of what to reteach. Anonymity matters, because the students least likely to admit confusion publicly are usually the ones you most need to hear from.",
        "how": [
            "Ask for one thing only. Muddiest point, singular.",
            "Genuinely anonymous. No names, no handwriting recognition in front of the class.",
            "Group the responses into two or three themes.",
            "Address the biggest theme at the start of the next lesson, and say where it came from.",
        ],
        "tech": "An anonymous response tool removes the paper handling and lets you sort themes in a couple of minutes rather than sifting slips.",
        "watch": "Collecting muddiest points and never addressing them teaches the class that the exercise is decorative, and the responses become perfunctory.",
    },
    "23": {
        "what": "Start every lesson with a brief review of prior content: yesterday's, last week's, last month's. Short, routine, non-negotiable.",
        "why": "Rosenshine put daily review first among his principles of instruction because the most effective teachers he observed did it consistently. It strengthens recall, surfaces gaps early and gives you a decision point: if most of the class can't answer, the pace of new teaching needs to change today rather than after the assessment.",
        "how": [
            "Build it into the lesson template so it's never a decision.",
            "Keep it to five minutes.",
            "Use whole-class response so you see everyone, not the volunteers.",
            "Act on it. If most of the room is blank, reteach rather than continue.",
        ],
        "tech": "A low-stakes quiz tool with a saved question bank makes the daily version sustainable across a full timetable.",
        "watch": "Review that always covers yesterday and never last month checks consolidation and never checks retention. Vary the intervals.",
    },
    "24": {
        "what": "Teach students to quiz themselves rather than reread their notes, and to space those self-quizzes over time.",
        "why": "Bjork's research is consistent on this: self-testing feels harder and less productive than rereading, and produces substantially better retention. The discomfort is the signal that it is working. Most students have never been told this, and they interpret the difficulty as evidence that the method isn't suiting them.",
        "how": [
            "Show them how: cover the notes, write what you remember, check, repeat on what was missing.",
            "Give them the schedule, not just the technique.",
            "Warn them it will feel worse than rereading. Say why.",
            "Follow up after the next assessment and ask what they actually did.",
        ],
        "tech": "Quizzing and flashcard tools handle the scheduling, and self-built decks add the benefit of writing the questions in the first place.",
        "watch": "Telling students to self-quiz without teaching the method produces flashcards with a whole paragraph on each side, which is rereading with extra steps.",
    },
}
