# -*- coding: utf-8 -*-
"""
Chapter 04 : Questioning & Discussion.
Expansions for each of the 24 strategies on the infographic.
"""

EXPANSIONS = {
    "01": {
        "what": "Anderson and Krathwohl's revision of Bloom sets out six cognitive processes: remembering, understanding, applying, analysing, evaluating and creating. It is a planning tool for questions, not a ladder to climb.",
        "why": "The common misreading treats recall as the low-value bottom rung to be escaped as fast as possible. It is not. Analysis without secure knowledge produces confident nonsense, and Willingham's point that you cannot think critically about content you do not know applies directly. The taxonomy is useful for making sure your questions span the range, not for ranking them by worth.",
        "how": [
            "Take a topic and write one question at each of the six levels.",
            "Notice which levels you find hard to write for. That is usually where your questioning is thin.",
            "Sequence them so the knowledge questions come before the ones that depend on that knowledge.",
            "Keep returning to remembering later in the unit, not just at the start.",
        ],
        "tech": "A question bank organised by level makes the range visible and stops the same three question types recurring across a unit.",
        "watch": "Treating the top three levels as the real teaching and recall as a warm-up produces students who can evaluate a topic they cannot describe.",
    },
    "02": {
        "what": "Hattie and Zierer separate surface questions, which establish what, deep questions, which establish why and how, and transfer questions, which ask students to apply the idea somewhere new.",
        "why": "Each type suits a different point in a sequence, and the common failure is reaching for transfer too early. A student who cannot yet explain the mechanism will not transfer it to an unfamiliar context; they will pattern-match on surface features and get it wrong. Knowing which type you are asking tells you whether a poor answer means reteach or means keep going.",
        "how": [
            "Label your planned questions surface, deep or transfer.",
            "Check the sequence moves in that order within a topic.",
            "Do not abandon surface questions once you have moved on. Interleave them back in.",
            "When transfer questions fail, drop back to deep rather than repeating the transfer.",
        ],
        "tech": "A slide or prompt display that keeps the question visible while students think reduces the load of holding a complex question in working memory.",
        "watch": "Deep questions asked of a class that has not secured the surface knowledge produce silence, which then gets misread as a discussion problem.",
    },
    "03": {
        "what": "A genuinely open question is one where you do not already have the answer in mind. Not a guess-what-I-am-thinking question with a wide opening.",
        "why": "Dillon's classroom research found that authentic questions, where the teacher was genuinely uncertain, produced markedly longer and more reasoned student responses. Students detect the difference quickly. When they sense a target answer, the task becomes finding it rather than thinking, and the reasoning shortens accordingly.",
        "how": [
            "Plan two or three genuinely open questions per unit, where multiple defensible answers exist.",
            "Do not evaluate the first answer. Collect several before responding to any.",
            "Let disagreement stand for a while rather than resolving it immediately.",
            "Be honest when you do have an answer in mind. Pseudo-open questions damage trust.",
        ],
        "tech": "A shared whiteboard or discussion board lets several answers exist at once, which is much harder to achieve in a sequence of spoken turns.",
        "watch": "Not every question should be open. Factual questions with one right answer are doing important work and should be asked as such.",
    },
    "04": {
        "what": "Write your key questions before the lesson rather than generating them in the moment.",
        "why": "Improvised questions default to recall, not because teachers undervalue thinking but because recall questions are the ones you can compose while also managing a room. Planning three or four questions in advance is one of the highest-return preparation tasks available, and it takes a couple of minutes.",
        "how": [
            "Plan three or four questions per lesson, not thirty.",
            "Write them where you will see them: on the slide, in the margin of the plan.",
            "Include at least one you expect the class to find difficult.",
            "Note what a wrong answer to each would tell you.",
        ],
        "tech": "Putting the questions on the slides means they are prepared, visible to students, and reusable next year.",
        "watch": "Planned questions still need responsive follow-ups. The plan is a floor for the quality of questioning, not a script to be read.",
    },
    "05": {
        "what": "Not every probe needs to be a question. Statements, invitations and silence often produce more than another question does.",
        "why": "Dillon found that non-question alternatives produced longer, more elaborated student responses than questions did. A question implies a specific answer is wanted and narrows the response. Tell me more, or a declarative statement offered for the class to react to, opens the space rather than closing it.",
        "how": [
            "Try a statement: I had not thought of it that way.",
            "Try an invitation: say more about that.",
            "Try silence. Count to five after an answer before speaking.",
            "Try reflecting back what was said and stopping.",
        ],
        "tech": "This is mostly a talk technique. Where technology helps is in recording a lesson so you can hear how often you ask versus how often you wait.",
        "watch": "Silence is only productive if the class knows what it is for. Establish that a pause is thinking time, or it will be filled with fidgeting.",
    },
    "06": {
        "what": "The pause between asking a question and expecting an answer. Rowe found most teachers wait under a second; three seconds changes what comes back.",
        "why": "Rowe's studies found that extending wait time to three seconds produced longer responses, more evidence and reasoning, more students volunteering, and fewer failures to respond. The mechanism is straightforward: complex answers take time to compose, and a one-second wait selects for whoever has an answer already, which is not the same as whoever is thinking hardest.",
        "how": [
            "Ask, then count silently to three before taking any answer.",
            "Tell the class you are doing it, so the silence is understood.",
            "Resist rephrasing during the pause. Rephrasing restarts the clock.",
            "Notice how uncomfortable it feels at first. It gets easier.",
        ],
        "tech": "A visible timer or countdown makes the wait a shared expectation rather than a test of your nerve.",
        "watch": "Wait time is the first thing to disappear when a lesson is running late, and it is the change most likely to improve the quality of answers.",
    },
    "07": {
        "what": "The second pause: after a student finishes speaking, before you respond. Also around three seconds.",
        "why": "Rowe identified this as the more neglected of the two and in some ways the more powerful. The pause after an answer prompts the student to elaborate, qualify or correct themselves, and signals to the room that more is expected. Filling it with an immediate evaluation ends the thinking at the first answer.",
        "how": [
            "When a student stops, do not speak. Count to three.",
            "Hold eye contact so the pause reads as interest rather than disapproval.",
            "Notice how often they add something unprompted.",
            "Only then respond, and prefer a follow-up question to an evaluation.",
        ],
        "tech": "Recording a lesson and listening back is the fastest way to find out how long you actually wait, which is almost always less than you think.",
        "watch": "A pause that reads as displeasure will silence a student rather than extend them. Your face is doing as much work here as the silence.",
    },
    "08": {
        "what": "Ask everyone to write an answer before any verbal response is taken.",
        "why": "Tobin's and Rowe's work on wait time points to the same underlying problem: the fastest student in the room sets the terms of the discussion. Writing first gives every student a position to hold. It also means that when you nominate, the student has something to read from, which removes most of the fear of being asked.",
        "how": [
            "Pose the question, then require writing before hands or nominations.",
            "Keep it short. A sentence is enough.",
            "Nominate after the writing, not before.",
            "Occasionally ask a student to read exactly what they wrote, including if they have changed their mind since.",
        ],
        "tech": "A shared document, whiteboard or response tool lets you see the range of positions before the discussion starts, which changes who you choose to bring in.",
        "watch": "For students with significant writing difficulties, requiring writing can create the barrier it was meant to remove. Allow a drawn or dictated equivalent.",
    },
    "09": {
        "what": "Lyman's structure: think alone, discuss in pairs, then share with the class. All three stages, in order.",
        "why": "The individual stage protects thinking time; the pair stage lets an idea be tested cheaply before public exposure; the share stage makes it accountable. It is one of the most widely used structures in teaching and one of the most frequently degraded, usually by dropping the first stage and turning it into unstructured chat.",
        "how": [
            "Time each stage visibly. Think is silent.",
            "Give the pair stage a task: agree an answer, or find where you differ.",
            "Nominate for the share rather than taking volunteers.",
            "Ask for the pair's position, which shares the exposure between two.",
        ],
        "tech": "A timer matters more than any dedicated tool here. Partner chat tools help when students are working remotely or in a large space.",
        "watch": "Without the silent think, the confident partner's first idea becomes the pair's answer and the structure has achieved nothing.",
    },
    "10": {
        "what": "Stop taking hands. Direct questions to named students instead, with the norm established in advance.",
        "why": "Wiliam's argument is that hands up creates a self-selecting minority who answer everything while the rest opt out, and that the opting out is invisible because the lesson appears to be going well. Removing hands makes participation a matter of your design rather than of student confidence, which is not evenly distributed.",
        "how": [
            "Explain the change and why, before you start.",
            "Pair it with wait time and with write-first, so being named is not an ambush.",
            "Allow a pass with a return: I will come back to you.",
            "Track who you have asked so the distribution is real rather than felt.",
        ],
        "tech": "A random name picker or class list tool removes unconscious bias in selection and makes the tracking automatic.",
        "watch": "Hands down without a supportive climate is exposure. The technique depends entirely on the norm that not knowing yet is acceptable.",
    },
    "11": {
        "what": "Direct questions to any student, in a climate where a wrong answer costs nothing and thinking aloud is expected.",
        "why": "Good and Brophy documented differential teacher questioning: higher-attaining students receive more, harder and more probing questions, and are given more time to answer. Cold calling is only equitable if the climate supports it. In a threatening room it amplifies the gap it was meant to close.",
        "how": [
            "Build the norms first: attempts are expected, not knowing yet is normal, we finish each other's thinking.",
            "Ask the same quality of question of every student.",
            "When an answer is wrong, work with it rather than moving on to someone else.",
            "Return to a student who passed, so the pass is not an exit.",
        ],
        "tech": "A random selector paired with a seating plan keeps selection visibly fair, which matters to students more than teachers often expect.",
        "watch": "Cold calling in a room where wrong answers get laughed at teaches students to stay silent, and the laughter is your responsibility to remove first.",
    },
    "12": {
        "what": "Keep a record of who you ask, what you ask them, and how long you give them.",
        "why": "Good and Brophy's finding is that the pattern is invisible from inside the lesson. Teachers believe they distribute questions evenly and the tallies say otherwise, consistently. Nothing changes the distribution as reliably as writing it down for a fortnight.",
        "how": [
            "Tally names against questions for two weeks.",
            "Note the type of question, not just the count.",
            "Look for who is missing and who only ever gets recall.",
            "Redesign your next unit's questioning around the gaps.",
        ],
        "tech": "A tracker or tally tool tied to your seating plan makes this survivable. Paper tallies work for a fortnight and rarely longer.",
        "watch": "Counting questions alone can flatter you. The type of question matters more than the number, and that is where the gap usually sits.",
    },
    "13": {
        "what": "Pose the question to everyone, pause for thinking, pounce on a named student, then bounce their answer to another student to extend or challenge.",
        "why": "Wiliam's structure keeps the whole class cognitively engaged because the bounce means any answer might land with anyone. It also breaks the teacher-student-teacher pattern that dominates most classroom talk, and it puts the evaluation of an answer into student hands rather than yours.",
        "how": [
            "Pose to the room. Do not name first, or everyone else disengages.",
            "Pause. Three seconds minimum.",
            "Pounce on a named student.",
            "Bounce: do you agree with that, and why? Then bounce again.",
        ],
        "tech": "A random name tool and a visible timer support the pounce and pause. The bounce is entirely a matter of your habit.",
        "watch": "Bouncing only to strong students to rescue an answer turns the technique into a repair mechanism and tells the class who is trusted.",
    },
    "14": {
        "what": "Alexander's five criteria for dialogic teaching: talk that is collective, reciprocal, supportive, cumulative and purposeful.",
        "why": "The five are useful as an audit because most classroom talk satisfies two or three. Talk is often collective and supportive and rarely cumulative, meaning ideas do not build across turns. Naming which criterion is missing gives you something specific to change rather than a general aspiration to have better discussions.",
        "how": [
            "Record or have a colleague observe fifteen minutes of your talk.",
            "Score it against the five criteria honestly.",
            "Pick the weakest and design for it specifically for a fortnight.",
            "Cumulative is usually the one to work on first.",
        ],
        "tech": "A lesson recording or observation tool gives you the evidence. Self-report on classroom talk is unreliable, including for very experienced teachers.",
        "watch": "Aiming at all five at once produces no change. One criterion, one fortnight.",
    },
    "15": {
        "what": "Initiation, Response, Evaluation is the default pattern of classroom talk: teacher asks, student answers, teacher judges. Replacing the evaluation with a follow-up question changes what the talk does.",
        "why": "Alexander and Mercer both identify IRE as the dominant and most limiting pattern. The evaluation closes the exchange: the answer has been judged, so there is nothing more to think about. Substituting a question keeps the thinking open and hands the next move back to the students.",
        "how": [
            "After an answer, ask what makes you say that, rather than saying good.",
            "Or hand it on: what does anyone else think about that?",
            "Withhold your judgement until several contributions have accumulated.",
            "Record yourself and count how many exchanges end in your evaluation.",
        ],
        "tech": "Video reflection or lesson capture is the only reliable way to see your own IRE rate, because it is almost invisible from the front of the room.",
        "watch": "Never evaluating is its own problem. Students need to know when something is right; the point is not to end every exchange that way.",
    },
    "16": {
        "what": "Mercer distinguishes three kinds of group talk: disputational, where students disagree without reasoning; cumulative, where they agree without challenge; and exploratory, where they challenge with reasons and build on each other.",
        "why": "Only exploratory talk is associated with improved outcomes, and it is the rarest of the three. Groups left to themselves default to cumulative, which looks collaborative and involves very little thinking. The distinction is worth teaching to students directly, because they can recognise which one they are doing.",
        "how": [
            "Teach the three types explicitly, with examples of each.",
            "Give sentence stems that force reasons: I disagree because, the evidence for that is.",
            "Listen for challenge. If there is none, the group is being cumulative.",
            "Ask groups to self-identify which type they were doing.",
        ],
        "tech": "Collaborative documents leave a trace of the reasoning, which lets you see whether challenge occurred rather than guessing from noise level.",
        "watch": "A quiet, agreeable group is often doing the least thinking in the room. Do not read harmony as productivity.",
    },
    "17": {
        "what": "Ground rules for talk, agreed with the class rather than displayed to them: how we disagree, how we give reasons, how we make sure everyone contributes.",
        "why": "Mercer's research found that explicitly teaching the ground rules of exploratory talk transformed the quality of group discussion, and that co-constructed rules outperformed rules that were given. Students who have argued about what a fair discussion looks like are considerably more likely to hold each other to it.",
        "how": [
            "Discuss what makes a good discussion before you set any group work.",
            "Draft the rules from their language and keep it to five or six.",
            "Display them and refer to them by number during group work.",
            "Revisit and revise them when they stop being followed.",
        ],
        "tech": "A shared document keeps the rules editable and lets students revise them, which matters if you want them to stay theirs.",
        "watch": "Rules that were co-constructed in September and never mentioned again become wallpaper by half term.",
    },
    "18": {
        "what": "Michaels, O'Connor and Resnick's accountable talk: students are held accountable to the learning community, to accurate knowledge, and to rigorous reasoning. Specific talk moves make this teachable.",
        "why": "The framework is useful because it names the moves rather than the aspiration. I agree because, the evidence is, can you say more, I want to build on what X said. These are learnable phrases that carry the reasoning with them, and students who use them are structurally more likely to give reasons.",
        "how": [
            "Teach four or five talk moves explicitly and display them.",
            "Model each one yourself in whole-class discussion.",
            "Require their use in group work initially, then let it become natural.",
            "Praise the move when you hear it, so the class notices it working.",
        ],
        "tech": "A sentence-starter display keeps the moves visible during discussion, which is when students need them and cannot recall them.",
        "watch": "Talk moves recited without the thinking behind them become a formula. Push past I agree because to what the reason actually is.",
    },
    "19": {
        "what": "Take a student's answer and hand it back to the class to extend, challenge or connect, rather than evaluating it yourself.",
        "why": "Alexander's dialogic teaching trial with the EEF found gains in English, maths and science, and the mechanism at the heart of it is teachers extending rather than evaluating. Returning an answer to the room positions you as the conductor of the thinking rather than the judge of it, and it makes listening to each other necessary rather than optional.",
        "how": [
            "Name the contribution: Aisha said X.",
            "Hand it on: who can add to that, or who sees it differently?",
            "Insist on engagement with the actual point, not a fresh answer.",
            "Return to the original student at the end to respond.",
        ],
        "tech": "A live display of contributions helps students track what has been said, which is what makes building on it possible in a long discussion.",
        "watch": "Handing on an answer that was wrong, without eventually resolving it, leaves the misconception in the room with a class that cannot tell.",
    },
    "20": {
        "what": "Teach students the stems for generating their own questions: why does, what would happen if, how does X compare with Y.",
        "why": "King's research found that students trained to generate questions using stems produced better discussion and better comprehension than students who only answered teacher questions. Generating a good question requires you to identify what matters, which is a substantially deeper act than answering one you have been given.",
        "how": [
            "Give a small set of stems, five or six, and display them.",
            "Model generating questions from a text or a diagram yourself.",
            "Require a specific mix: one why, one what if, one comparison.",
            "Use the best of their questions in the next lesson, credited.",
        ],
        "tech": "Question stem cards or a display keep the stems available at the point of use, which is where the scaffold does its work.",
        "watch": "Without stems, most students generate recall questions, and conclude that question generation is a low-value task.",
    },
    "21": {
        "what": "Students generate questions and pose them to each other, with neither party holding a model answer.",
        "why": "King's reciprocal peer questioning produces genuine enquiry rather than rehearsal, because there is no answer key to converge on. The questioner has to judge whether an answer is adequate, which requires them to understand the material at least as well as the responder. Both roles are cognitively demanding, which is the point.",
        "how": [
            "Teach the stems first. This does not work cold.",
            "Pair students and give each a section of content to question the other on.",
            "Require follow-up questions, not just an exchange of one question each.",
            "Circulate and listen for the quality of the questions rather than the answers.",
        ],
        "tech": "Pair chat or response tools keep a record of the exchange, which lets you review the questioning quality after the lesson.",
        "watch": "Pairs of similar attainment can converge on a shared misconception with nobody in the room to notice. Circulate purposefully.",
    },
    "22": {
        "what": "Use the questions students ask as evidence of understanding. Ask for one written question at the end of a lesson.",
        "why": "A question reveals the edge of what someone knows. Why does X cause Y demonstrates a grasp of the relationship; what is X demonstrates that the basics have not landed. King's work on question generation and Wiliam's on eliciting evidence meet here: the question is diagnostic data that costs two minutes to collect.",
        "how": [
            "One written question at the end of the lesson, from everyone.",
            "Sort them into recall, explanation and application before the next lesson.",
            "The distribution tells you where the class actually is.",
            "Answer the best ones publicly and credit them.",
        ],
        "tech": "An exit ticket or response tool collects and sorts thirty questions in the time it takes to gather thirty slips of paper.",
        "watch": "Students who have learned that questions signal weakness will write safe ones. The climate has to make curiosity look like competence.",
    },
    "23": {
        "what": "Mercer's interthinking: the shared cognition that happens when a group genuinely thinks together through language, rather than dividing the task up.",
        "why": "The concept is useful because it names what good group work is for. If the outcome could have been produced by one person working alone, the group added nothing. Student questions sustain joint enquiry because they keep the group working on the same problem rather than on parallel fragments of it.",
        "how": [
            "Set tasks that genuinely require more than one mind, not tasks that can be split.",
            "Require a shared product that everyone can explain.",
            "Ask any group member to account for the group's reasoning.",
            "Value the questions the group asked as much as the answer it reached.",
        ],
        "tech": "Collaborative writing tools show whether thinking was shared or divided, because the edit history makes the division visible.",
        "watch": "Group tasks that decompose neatly into individual chunks produce efficient division of labour and no interthinking at all.",
    },
    "24": {
        "what": "Use student questions to open a topic. What do you already know, and what do you want to know, becomes the entry point for the enquiry.",
        "why": "King found that connecting new questions to prior knowledge produced the strongest learning effects. Starting from what students actually wonder about does two things at once: it activates the prior knowledge you need them to connect to, and it tells you where their existing understanding is, before you have taught anything.",
        "how": [
            "Open a topic by collecting what they know and what they want to know.",
            "Sort their questions into ones the unit will answer and ones it will not.",
            "Display the list and tick them off as the unit progresses.",
            "Return to the unanswered ones at the end and decide together what to do with them.",
        ],
        "tech": "A shared board or survey tool collects thirty contributions in two minutes and keeps them visible for the length of the unit.",
        "watch": "Collecting student questions and then teaching the unit exactly as planned, without reference to them, teaches the class that their questions are decorative.",
    },
}
