# -*- coding: utf-8 -*-
"""
Chapter 05 : Explanations & Modelling.
Expansions for each of the 24 strategies on the infographic.
"""

EXPANSIONS = {
    "01": {
        "what": "Present new material in small steps, with practice after each step, rather than delivering the whole explanation and then setting the task.",
        "why": "Rosenshine's principle rests on working memory limits. A long uninterrupted explanation asks students to hold everything until the end, and most can't. Breaking it into steps with practice between them keeps the load manageable and gives you a check at each stage, which means errors surface before they compound.",
        "how": [
            "Split the explanation into three or four steps that each make sense alone.",
            "After each step, a short practice: one question, one example, one attempt.",
            "Check before continuing. Whole-class response, not a nod.",
            "Reveal the next step only when the previous one is secure.",
        ],
        "tech": "Slide animations and progressive reveal keep the display matched to the step you're on, so students aren't reading ahead while you're still explaining.",
        "watch": "Steps that are too small fragment the idea and hide the shape of it. The step should be a whole thought, not a whole sentence.",
    },
    "02": {
        "what": "Anchor a new abstract idea to something concrete first: an image, an object, a worked case. Name the abstraction afterwards.",
        "why": "Willingham's argument is that we understand new ideas in terms of things we already know, and that concrete examples provide the hooks. Starting with the definition asks students to attach meaning to a term that has nothing behind it yet. Starting with the example gives them something to abstract from.",
        "how": [
            "Choose two or three concrete examples before you plan the definition.",
            "Show them and ask what they have in common.",
            "Name the concept only once the pattern is visible to the class.",
            "Return to the concrete when the abstraction wobbles later.",
        ],
        "tech": "A visualiser, image or short video clip puts the concrete in front of the class quickly, which is often what stops this happening in practice.",
        "watch": "Examples that share surface features but not the underlying structure teach the wrong pattern. Vary the surface, hold the structure constant.",
    },
    "03": {
        "what": "Activate what students already know before introducing anything new, so the new material has somewhere to attach.",
        "why": "Rosenshine puts daily review among his principles for this reason: new learning is built on existing schema, and material that connects to nothing is far harder to retain. A retrieval starter does double duty here, strengthening the prior knowledge and priming the connection you're about to ask them to make.",
        "how": [
            "Identify the specific prior knowledge today's lesson depends on.",
            "Retrieve it at the start, actively rather than by reminding them.",
            "Make the link explicit: this is why we needed that.",
            "If the prior knowledge isn't there, teach that first rather than continuing.",
        ],
        "tech": "A concept map or retrieval tool surfaces the existing structure so students can see where the new content is going to sit.",
        "watch": "Reminding students of prior knowledge isn't the same as retrieving it. Telling them again strengthens nothing.",
    },
    "04": {
        "what": "Choose the presentation method that makes the idea clearest, not the one that's newest or most impressive.",
        "why": "The EEF's digital technology guidance is consistent on this: the evidence favours clarity of explanation over any particular medium, and technology that adds production values without adding clarity adds nothing. A hand-drawn diagram building live under a visualiser frequently beats a polished animation, because the class sees it being constructed.",
        "how": [
            "Ask what the hardest part of this idea is to grasp.",
            "Choose the medium that makes that specific part visible.",
            "Prefer live construction to finished artefacts where the process matters.",
            "Be willing to use the simplest possible tool if it's the clearest.",
        ],
        "tech": "Any display tool used with purpose. The question is never what the tool can do, it's what the students need to see.",
        "watch": "Time spent making a resource look impressive is time not spent on whether it explains the thing. The two are easy to confuse while making it.",
    },
    "05": {
        "what": "Check understanding at every step of an explanation rather than at the end, and reteach before moving on.",
        "why": "Rosenshine found that the most effective teachers checked understanding frequently and were prepared to reteach. Listening is not learning, and a class that is quiet and attentive can be almost entirely lost. The check has to sample everyone, because the students who signal confusion aren't the ones you most need to hear from.",
        "how": [
            "Plan the check points into the explanation, don't improvise them.",
            "Use whole-class response so you see everyone.",
            "Set a threshold in advance: if fewer than most are secure, reteach.",
            "Reteach differently rather than repeating the same words louder.",
        ],
        "tech": "Live polling or mini whiteboard tools give you the whole room in seconds, which is what makes frequent checking realistic.",
        "watch": "Any questions? is not a check. It samples confidence, not understanding, and it selects for the students least likely to need help.",
    },
    "06": {
        "what": "Technology should add to your explanation, not replace it. A screencast works alongside classroom teaching, not instead of it.",
        "why": "The EEF's conclusion across multiple reviews is that technology has most impact when it supplements teaching rather than substituting for it. The mechanism isn't mysterious: a recording can't read the room, can't notice the confused expression, and can't change tack. It can, however, be paused and rewatched, which live teaching can't.",
        "how": [
            "Teach it live, with checks and adaptation.",
            "Provide the recorded version for revision and for absence.",
            "Do not set the video as the first encounter with a difficult idea.",
            "Use the recording to free lesson time for practice and feedback.",
        ],
        "tech": "A screencast plus an LMS for replay access covers both cases: the live teaching and the on-demand version students return to.",
        "watch": "Videos assigned instead of teaching disadvantage exactly the students who most need the responsiveness of a teacher in the room.",
    },
    "07": {
        "what": "Working memory holds roughly four items at once. Every element on the screen competes for those slots, including the ones you didn't intend as content.",
        "why": "Sweller's cognitive load theory distinguishes the load intrinsic to the material from the extraneous load added by how it's presented. Decorative images, dense slides and background detail all consume capacity that was needed for the actual thinking. Blanking the screen when you want attention on you is the simplest available intervention.",
        "how": [
            "Strip slides to what is needed for this step.",
            "Press B or W to blank the screen when you're talking and the slide isn't needed.",
            "One idea per slide. If it needs two, it needs two slides.",
            "Ask of every element: what is this doing for the learning?",
        ],
        "tech": "The B and W keys in PowerPoint and Keynote are the most underused accessibility and attention feature available, and they cost nothing.",
        "watch": "Sparse slides can be mistaken for unprepared ones. The preparation went into deciding what to leave out.",
    },
    "08": {
        "what": "Keep labels, text and the image they refer to together. Do not make students search between a diagram and a separate key.",
        "why": "Sweller's split attention effect describes the load imposed when learners must integrate two sources of information that are physically separated. The searching and holding is extraneous load, spent on logistics rather than learning. Integrating the label into the diagram removes the cost entirely.",
        "how": [
            "Put labels on the diagram, not in a legend beside it.",
            "Keep an explanation next to the part it explains.",
            "Where a key is unavoidable, keep it visually adjacent.",
            "Build diagrams live with annotation so labels arrive where they belong.",
        ],
        "tech": "Annotation tools let you label as you go, which also paces the diagram to your explanation rather than presenting it complete.",
        "watch": "Textbooks and exam papers frequently split attention by design. Worth naming that with students so they know the difficulty is in the format.",
    },
    "09": {
        "what": "Do not read out text that's already on the screen. Say it or show it, not both.",
        "why": "Sweller's redundancy effect: identical information presented simultaneously in two forms increases load rather than reinforcing. The learner can't easily ignore either channel, so they process both and reconcile them, which costs capacity. This is one of the most common and most easily fixed problems in classroom presentation.",
        "how": [
            "If you're going to talk through it, blank the screen.",
            "If the text needs reading, give silent reading time and stay quiet.",
            "Use the screen for what speech can't do: diagrams, images, data.",
            "Keep on-screen text to short prompts rather than full sentences you'll narrate.",
        ],
        "tech": "The B or W key again. It costs one keystroke and removes the redundancy instantly.",
        "watch": "This doesn't apply to captions or to students who need the text for access. Redundancy for cognitive load and redundancy for accessibility are different questions.",
    },
    "10": {
        "what": "Remove every word, image and sound that doesn't support the learning. Clip art, background music, decorative borders.",
        "why": "Mayer's coherence principle is that people learn better when extraneous material is excluded. The finding is counterintuitive because the extra material is usually added to increase engagement, and it does increase engagement while reducing learning. Interest generated by decoration competes with the content rather than serving it.",
        "how": [
            "Audit a set of your slides and remove everything that isn't doing work.",
            "Be ruthless about images that illustrate the topic but not the point.",
            "Cut background music entirely during explanation.",
            "Adopt a plain template so the default is clean.",
        ],
        "tech": "A minimal slide template makes the clean version the path of least resistance, which is the only reliable way to sustain this.",
        "watch": "Coherence is not the same as dullness. An image that carries the meaning belongs; an image that fills the space doesn't.",
    },
    "11": {
        "what": "Direct attention explicitly: bold the key term, arrow the relevant part, highlight the line you're discussing.",
        "why": "Mayer's signalling principle finds that cues which highlight the organisation of the material improve learning. Without them, learners spend capacity working out where to look, and they don't always choose correctly. The signal is cheap and it removes a search task that has nothing to do with the content.",
        "how": [
            "Highlight or arrow the part you're talking about, as you talk about it.",
            "Signal structure as well as detail: first, second, the key point is.",
            "Keep signals sparse. Highlighting everything signals nothing.",
            "Remove the signal once the class knows where to look.",
        ],
        "tech": "Live annotation is more effective than pre-marked slides because the signal appears at the moment attention needs to move.",
        "watch": "Pre-highlighted handouts signal to the reader before they've read, which can prevent them noticing what mattered themselves.",
    },
    "12": {
        "what": "Break content into segments and let the learner control, or at least pace, the movement between them.",
        "why": "Mayer's segmenting principle finds that learning improves when material is delivered in learner-paced chunks rather than a continuous stream. Working memory needs time to process each segment before the next arrives. Auto-advancing animation removes the pause that the processing requires.",
        "how": [
            "One idea per click, not per timer.",
            "Pause between segments and check before continuing.",
            "In recorded material, keep videos short and single-idea rather than long and comprehensive.",
            "Let students control the pace where the format allows it.",
        ],
        "tech": "Slide animation set to on click rather than after previous. It's a two-second setting change with a real effect on comprehension.",
        "watch": "Segmenting a poorly organised explanation just produces poorly organised fragments. The structure has to be right first.",
    },
    "13": {
        "what": "Design each slide with a key visual and minimal text, so the same idea arrives through two channels rather than one.",
        "why": "Paivio's dual coding theory holds that verbal and visual information are processed through partly separate channels, and that material encoded in both is better retained. This has nothing to do with learning styles. It's a question of using more of the available processing capacity for the same idea.",
        "how": [
            "For each key idea, decide what the visual is before you write the text.",
            "Keep the text to a phrase, not a sentence.",
            "Make the visual carry meaning, not decoration.",
            "Ask students to reproduce the visual from memory later.",
        ],
        "tech": "Dual coded slide design is a habit rather than a tool. Any presentation software supports it; most templates encourage the opposite.",
        "watch": "This is not learning styles. Everyone benefits from dual coding; nobody is a visual learner who should be given only pictures.",
    },
    "14": {
        "what": "When you've a diagram or animation, narrate it rather than labelling it with paragraphs of text.",
        "why": "Mayer's modality principle finds that people learn better from graphics with spoken narration than from graphics with printed text. The reason is channel capacity: the visual channel is already handling the diagram, and adding text loads it further, while the auditory channel is free.",
        "how": [
            "Where you'd write an explanatory paragraph beside an image, say it instead.",
            "For recorded material, narrate over the visual rather than captioning it.",
            "Keep essential labels on the diagram; move the explanation to speech.",
            "Provide a transcript so the spoken version isn't the only route.",
        ],
        "tech": "Screen recording with voiceover produces this naturally, and the recording can be revisited in a way that live narration can't.",
        "watch": "Narration alone excludes deaf students and anyone in a noisy environment. Captions and transcripts are not optional extras.",
    },
    "15": {
        "what": "Place words physically near the part of the image they describe, rather than in a block above or below.",
        "why": "Mayer's spatial contiguity principle is the presentation-design counterpart of Sweller's split attention. Distance between related elements imposes a search cost. Proximity removes it. The effect is larger than most people expect for a change that's purely about layout.",
        "how": [
            "Move labels onto the diagram, adjacent to what they name.",
            "Keep captions next to their image, not at the foot of the slide.",
            "Where a step-by-step explanation accompanies a diagram, place each step by the relevant part.",
            "Check on the actual display size. What is adjacent on your laptop may not be at the back of the room.",
        ],
        "tech": "Integrated slide layout, which mostly means overriding the default text-box positions your template provides.",
        "watch": "Cramming text onto an image to achieve proximity can make both unreadable. Sometimes the answer is a simpler diagram.",
    },
    "16": {
        "what": "Reveal a complex visual one element at a time, building the full picture as your explanation progresses.",
        "why": "This combines Mayer's segmenting with Sweller's load management. A complete diagram presented at once invites the learner to process all of it while you're explaining one part. Building it live means what is on screen matches what is being said, and the construction itself shows the relationships between parts.",
        "how": [
            "Build the animation to match the order of your explanation.",
            "One element per click.",
            "Pause after each addition.",
            "Show the completed version at the end so students see the whole.",
        ],
        "tech": "Appear-on-click animation. Avoid movement effects, which add processing cost without adding meaning.",
        "watch": "Progressive reveal used for suspense rather than for load management just slows the lesson down.",
    },
    "17": {
        "what": "Short recorded explanations with narration over a visual. One idea per video.",
        "why": "Mayer's multimedia and modality principles together favour images plus voice over text-heavy slides, and the recorded format adds learner control over pace. The brevity matters more than the production quality: a two-minute clip on one idea will be rewatched, and a fifteen-minute comprehensive one won't.",
        "how": [
            "One idea, two to four minutes.",
            "Script the first and last sentences, improvise the middle.",
            "Show your working on screen rather than talking over a finished result.",
            "Caption them, or use a platform that captions accurately.",
        ],
        "tech": "Any screen recording tool. Do not spend time editing; the value is in the explanation and the availability, not the polish.",
        "watch": "A library of long videos nobody watches is a substantial investment of your time for very little return. Keep them short or do not make them.",
    },
    "18": {
        "what": "Teach the key vocabulary before the main explanation, so students aren't decoding terms and following an argument simultaneously.",
        "why": "Mayer's pre-training principle finds that learning improves when learners already know the names and characteristics of the main components before the process is explained. Unfamiliar terminology consumes working memory that the explanation needs. Front-loading it means the explanation itself has room to land.",
        "how": [
            "Identify the terms in your explanation that will be new.",
            "Teach those first, briefly, with examples.",
            "Check recall of the terms before beginning the explanation.",
            "Keep the terms visible during the explanation.",
        ],
        "tech": "A vocabulary slide or a short pre-lesson video builds the familiarity outside the lesson, which returns lesson time to the explanation.",
        "watch": "Pre-teaching a long list of terms with no context becomes rote definition learning. Keep it to the terms the explanation actually needs.",
    },
    "19": {
        "what": "Model the process rather than presenting the product. Work through it live and narrate the decisions as you make them.",
        "why": "Rosenshine's emphasis on modelling and worked examples rests on making expert thinking visible. A finished exemplar shows the destination; it doesn't show the route. The decisions an expert makes without noticing, where to start, what to discard, when to check, are exactly the parts novices lack.",
        "how": [
            "Work a live example rather than displaying a prepared one.",
            "Narrate the decisions, including the ones you reject.",
            "Include a deliberate wrong turn and show how you notice and recover.",
            "Keep the pace slow enough that students can follow the thinking, not just the writing.",
        ],
        "tech": "A visualiser or screen share with narration is the simplest way to do this. The class needs to see the hand or the cursor moving.",
        "watch": "Modelling that is too fluent hides the process. If it looks effortless, students conclude the difficulty is in them.",
    },
    "20": {
        "what": "A visualiser turns any desk into a modelling stage: handwriting, annotation, diagram construction, student work shown live.",
        "why": "The EEF has identified visualisers among the more promising classroom technologies, and the reason is how directly they serve modelling and feedback. They remove the friction between having something worth showing and showing it, which is the friction that stops most live modelling happening.",
        "how": [
            "Model handwriting and setting out, not just content.",
            "Show student work live, with permission, to critique against criteria.",
            "Annotate texts under the camera so the annotation is a shared act.",
            "Build diagrams by hand so the construction sequence is visible.",
        ],
        "tech": "A visualiser or document camera. A phone on a stand with a screen share does the same job if a dedicated device isn't available.",
        "watch": "Showing student work without establishing a critique culture first can expose a student. Set the norms before the first time you do it.",
    },
    "21": {
        "what": "A recorded worked example students can pause, rewind and study at their own pace.",
        "why": "Sweller and Cooper's worked example effect found that novices learn more from studying worked examples than from solving equivalent problems, because problem solving consumes capacity on search rather than on the method. Recording the example adds learner control, which lets students revisit the step they didn't follow.",
        "how": [
            "Record the example with narration of the reasoning, not just the steps.",
            "Keep it to one problem type.",
            "Ask students to watch, then reproduce it from memory before attempting a new problem.",
            "Pair it with a parallel problem to attempt immediately after.",
        ],
        "tech": "Screen recording plus an LMS for sharing. The pause and rewind is the pedagogical feature, so keep the file easy to reach.",
        "watch": "The worked example effect reverses as expertise grows. Experienced students learn more from problem solving, so fade the examples as they become fluent.",
    },
    "22": {
        "what": "Alternate worked examples with practice problems: example, try one, example, try one.",
        "why": "Atkinson's and Sweller's work found example-problem pairs more effective than blocks of examples followed by blocks of problems. The alternation means the method is fresh at the point of attempting it, and the attempt reveals whether the example was understood before three more examples have gone by.",
        "how": [
            "Structure practice as pairs rather than blocks.",
            "Keep the practice problem parallel to the example, not a variation.",
            "Check after each attempt before moving to the next example.",
            "Increase the distance between example and problem as competence grows.",
        ],
        "tech": "Displaying the example alongside the task means students can refer back without turning pages, which reduces split attention.",
        "watch": "If the practice problem is too different from the example, students can't bridge the gap and the pairing doesn't help.",
    },
    "23": {
        "what": "Move from a complete worked example, to a partially completed one with steps missing, to independent practice.",
        "why": "Rosenshine's guidance on scaffolds and Sweller's on completion problems point the same way. A partially completed example carries less load than a blank problem while still requiring the student to do the thinking at the missing step. Fading the support in stages is what transfers the method from you to them.",
        "how": [
            "Plan three stages: complete, partial, blank.",
            "Choose which step to remove first based on where the difficulty is.",
            "Remove more steps each time.",
            "Only reach independent practice when the partial version is reliable.",
        ],
        "tech": "Fillable templates or shared documents make producing the partial versions quick, which is what usually prevents this being done properly.",
        "watch": "Scaffolds that never fade produce dependency. Plan the removal at the same time as you plan the support.",
    },
    "24": {
        "what": "Use simulations to let students manipulate variables and see consequences that are impossible, dangerous or too slow in a real classroom.",
        "why": "The EEF's review of digital technology identifies simulations as valuable where they let learners explore relationships that couldn't otherwise be observed. Changing the mass of a planet, running a reaction a hundred times, compressing geological time. Used to extend an explanation this is powerful; used to replace one it removes the teacher from the part that needed judgement.",
        "how": [
            "Explain the underlying idea first.",
            "Give a specific investigative question, not free exploration.",
            "Require a prediction before they run the simulation.",
            "Debrief against the explanation so the simulation is connected back to the theory.",
        ],
        "tech": "Simulation and interactive modelling tools. Choose ones where the variables map to what you're teaching, not ones with the most features.",
        "watch": "Unstructured time on a simulation produces engagement and very little learning. The prediction and the debrief are where the value sits.",
    },
}
